// =============================================================================
// CRYPTOGRAPHY TRACK — three modules.
// -----------------------------------------------------------------------------
// docs/research/CURRICULUM_PLAN.md had not reached this track when this content was
// authored (the published file covers `oop` and `dbms` and is marked CHUNK-2), so
// the module ladder here is this stream's own outline. It follows the plan's slug
// convention (`crypto-` prefix) so the two do not collide when the plan lands, and
// it obeys the plan's own stated constraint for the track.
//
// THE NON-NEGOTIABLE RULE FOR THIS TRACK: browser `SubtleCrypto` only.
//
// Every lab calls `crypto.subtle` — the platform's own reviewed implementation,
// available in a Web Worker in any secure context, which is where the JS runner
// executes. No third-party crypto library, no npm dependency, and no from-scratch
// cipher presented as usable. Where a lab implements something by hand to show how
// it fails (the XOR "cipher" in module 3), the step carries
// `notProductionReady: true`, which renders as a prominent on-screen warning — a
// student who copies that code out of here must not have to infer it.
//
// The teaching stance throughout is "use the primitive correctly", not "build the
// primitive". The failures shown are the ones that appear in real code review:
// hashing a password, ECB patterning, IV reuse, and non-constant-time comparison.
// =============================================================================

import type { SeedModule } from "./types";

export const cryptographyModules: SeedModule[] = [
  // -------------------------------------------------------------------------
  {
    slug: "crypto-hashing-and-integrity",
    track: "cryptography",
    title: "Hashing and Integrity",
    summary:
      "A hash proves a message has not changed. It does not hide it, it does not prove who sent it, and knowing which of those three problems you have is most of the skill.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest",
      "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign",
    ],
    steps: [
      {
        kind: "explain",
        title: "What a hash is for",
        body: [
          "A cryptographic hash maps input of any length to a fixed-length digest, with three",
          "properties that matter:",
          "",
          "**Deterministic.** The same input always gives the same digest, so two parties can",
          "compute it independently and compare.",
          "",
          "**Avalanche.** Change one bit of input and roughly half the output bits flip. There is",
          "no partial similarity to exploit and no way to steer the output.",
          "",
          "**One-way, and collision-resistant.** Given a digest you cannot compute the input, and",
          "you cannot find two inputs sharing a digest.",
          "",
          "Now the part people get wrong. A hash gives you **integrity**, and only integrity.",
          "",
          "It is not encryption — the digest is public and the message is not recoverable from it,",
          "which is a different thing from the message being hidden. It is not authentication",
          "either: anyone can hash anything, so a matching digest proves the bytes are intact, not",
          "who produced them. If an attacker can change the message, they can change the digest",
          "sitting next to it, and both will agree.",
          "",
          "Authentication needs a key. That is what HMAC and signatures are, later in this module.",
        ].join("\n"),
        diagram: {
          title: "What a digest does and does not prove",
          frames: [
            {
              label: "Same input, same digest",
              caption:
                "Deterministic. Two machines that never spoke can compute the same value and compare it.",
              code: 'sha256("invoice-42") -> 5f2c...  (always)',
            },
            {
              label: "One bit changes everything",
              caption:
                "Avalanche: a single character produces a completely unrelated digest. There is no near-miss to exploit.",
              code: 'sha256("invoice-43") -> b91e...  (unrelated)',
            },
            {
              label: "Integrity, not secrecy",
              caption:
                "The digest travels in the open. It tells a recipient the bytes are intact; it hides nothing about them.",
              code: "message + digest  ->  recipient re-hashes and compares",
            },
            {
              label: "Integrity, not authenticity",
              caption:
                "An attacker who can rewrite the message can rewrite the digest beside it. Both agree, and nothing detects it. Only a key fixes this.",
              code: "attacker: message' + sha256(message')  -> looks valid",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Digest with SubtleCrypto",
        language: "javascript",
        goal:
          "Hash two nearly identical strings with SHA-256 and compare the digests, then hash a large input and note that the digest length does not change.",
        hint:
          "`crypto.subtle.digest` takes bytes, not a string: encode first with `new TextEncoder().encode(text)`. It returns an ArrayBuffer, so wrap it in `new Uint8Array(...)` to read the bytes.",
        starterCode: [
          "// SubtleCrypto is the browser's own reviewed implementation. This is the",
          "// only crypto you should ever call in a browser.",
          "",
          "async function sha256Hex(text) {",
          "  const bytes = new TextEncoder().encode(text);",
          "  const digest = await crypto.subtle.digest('SHA-256', bytes);",
          "  return [...new Uint8Array(digest)]",
          "    .map((b) => b.toString(16).padStart(2, '0'))",
          "    .join('');",
          "}",
          "",
          "console.log(await sha256Hex('invoice-42'));",
          "console.log(await sha256Hex('invoice-43'));",
          "",
          "// TODO: how many hex characters is each digest? Is that a coincidence?",
          "// TODO: hash a 100 000-character string and check the digest length again.",
          "// TODO: hash the empty string. Does it have a digest?",
        ].join("\n"),
        body: [
          "`await` works at the top level of this editor, so you can call these directly.",
          "",
          "Answers to check yourself against: 64 hex characters, because SHA-256 produces 256",
          "bits and each hex character carries 4. It does not change with input size — that is",
          "what \"fixed-length\" means, and it is why a digest can be stored in a fixed column.",
          "The empty string has a perfectly good digest; \"no input\" is still an input.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Comparing digests in constant time",
        body: [
          "You have a digest and a value someone sent you. The obvious comparison has a flaw:",
          "",
          "```js",
          "if (received === expected) { /* accept */ }",
          "```",
          "",
          "String comparison stops at the first differing character. So a value whose first byte",
          "is wrong is rejected marginally faster than one whose first three bytes are right. That",
          "difference is tiny, but it is *information*, and an attacker who can make many attempts",
          "and time them can recover the expected value one byte at a time — turning an infeasible",
          "search into a linear one.",
          "",
          "The fix is to compare every byte regardless:",
          "",
          "```js",
          "function equalBytes(a, b) {",
          "  if (a.length !== b.length) return false;   // length is not secret",
          "  let diff = 0;",
          "  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];",
          "  return diff === 0;",
          "}",
          "```",
          "",
          "No early exit, so the running time depends on the length and not on the contents.",
          "",
          "Two caveats, because this is a place where confident advice goes wrong. This pattern is",
          "*not* reliably constant-time in a JIT-compiled language — the engine may optimise it —",
          "so on a server use the platform's own function (`crypto.timingSafeEqual` in Node). And",
          "it matters only where an attacker can both trigger many comparisons and observe the",
          "timing. That is real for an API token or an HMAC tag over a network; it is not the",
          "practical attack on a high-entropy secret behind a full HTTPS round trip, which is why",
          "this repository's own cron guard documents that choice explicitly rather than pretending",
          "otherwise.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "What does a matching digest prove?",
        prompt:
          "A file arrives with a SHA-256 digest published on the same web page. The digest matches. What have you established?",
        options: [
          {
            text: "The file matches that digest — nothing about who produced either, since an attacker able to alter one could alter both",
            correct: true,
          },
          { text: "The file came from the site's owner, because only they could compute the digest" },
          { text: "The file has not been read by anyone in transit" },
          { text: "The file contains no malicious content" },
        ],
        explanation:
          "Anyone can compute a SHA-256 digest — that is the point of a public hash function. If the attacker controls the channel that delivered the file, it controls the channel that delivered the digest, so a match proves only internal consistency. The digest is genuinely useful against accidental corruption and against a compromised mirror when the digest came from somewhere else. Establishing origin needs a key: an HMAC with a shared secret, or a signature verified against a public key you already trusted.",
        body: "Practical question, and the wrong answer is a common belief about download pages.",
      },
      {
        kind: "explain",
        title: "HMAC and signatures — adding a key",
        body: [
          "To prove *who* produced a message you need something the attacker does not have.",
          "",
          "**HMAC** mixes a shared secret key into the hash. Both sides know the key, so both can",
          "compute the tag, and nobody else can. That covers webhook verification, session cookie",
          "integrity, signed URLs — anywhere the same party issues and checks.",
          "",
          "```js",
          "const key = await crypto.subtle.importKey(",
          "  'raw', secretBytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign', 'verify']);",
          "const tag = await crypto.subtle.sign('HMAC', key, messageBytes);",
          "```",
          "",
          "**A signature** uses a key *pair*: the holder of the private key signs, and anyone with",
          "the public key verifies. Because verification needs no secret, a signature also gives",
          "you non-repudiation — the signer cannot plausibly deny it, since nobody else could have",
          "produced it. That is what HMAC cannot do: with a shared key, either party could have",
          "made the tag.",
          "",
          "Note `false` in the `importKey` call above: it marks the key non-extractable, so",
          "JavaScript can use it but not read its bytes back out. Passing `true` without needing",
          "to is a habit worth not forming.",
          "",
          "And verify with `crypto.subtle.verify`, not by computing the tag yourself and comparing",
          "with `===`. The platform function is the one that has thought about the timing.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Sign and verify with HMAC",
        language: "javascript",
        goal:
          "Produce an HMAC tag for a message, verify it, then tamper with one character of the message and watch verification fail.",
        hint:
          "`crypto.subtle.verify('HMAC', key, tag, messageBytes)` returns a boolean — use it rather than comparing tags yourself.",
        starterCode: [
          "const enc = new TextEncoder();",
          "",
          "// In real code this key comes from configuration, never from source.",
          "const key = await crypto.subtle.importKey(",
          "  'raw',",
          "  enc.encode('a-shared-secret-that-would-live-in-config'),",
          "  { name: 'HMAC', hash: 'SHA-256' },",
          "  false,                 // non-extractable: usable, not readable",
          "  ['sign', 'verify'],",
          ");",
          "",
          "const message = 'transfer 100 to account 7';",
          "const tag = await crypto.subtle.sign('HMAC', key, enc.encode(message));",
          "",
          "console.log('verified original:',",
          "  await crypto.subtle.verify('HMAC', key, tag, enc.encode(message)));",
          "",
          "// TODO: verify the SAME tag against 'transfer 900 to account 7'.",
          "// TODO: try flipping one character of the message. Does the tag ever nearly match?",
          "// TODO: why is importKey called with `false` for extractable?",
        ].join("\n"),
        body: [
          "This is the shape of every webhook verification you will ever write: recompute the tag",
          "over the exact bytes received and ask the platform whether it matches.",
          "",
          "Two things real implementations get wrong. They verify over a re-serialised body rather",
          "than the raw bytes, so a harmless whitespace change breaks the tag. And they compare the",
          "tag with `===` instead of calling `verify`. Use `verify`.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "crypto-password-storage",
    track: "cryptography",
    title: "Storing Passwords",
    summary:
      "Passwords are not encrypted and not hashed with SHA-256. They go through a deliberately slow key-derivation function, and the reason is arithmetic.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",
      "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveBits",
    ],
    steps: [
      {
        kind: "explain",
        title: "Never encrypted, and never a fast hash",
        body: [
          "Two wrong answers first, because both are common.",
          "",
          "**Encryption is wrong** because encryption is reversible by design. Whoever holds the",
          "key can recover every password, so the key becomes a single object whose compromise",
          "loses everything — and the key has to be somewhere the login code can reach it, which",
          "is to say, next to the database. You never need to recover a password; you only need to",
          "check one. So do not store something recoverable.",
          "",
          "**A plain fast hash is wrong** for a reason that is pure arithmetic. SHA-256 is",
          "designed to be fast, and modern hardware computes it in the billions per second. An",
          "attacker with your table does not need to reverse the hash — they hash guesses until",
          "one matches. At those rates, every password in any wordlist, and every short password,",
          "falls within hours.",
          "",
          "The right tool is a **password hashing function** — Argon2id, scrypt, bcrypt, or",
          "PBKDF2 — which is deliberately expensive. Same guess-and-compare attack, but each",
          "guess now costs milliseconds and real memory instead of nanoseconds. That is a factor",
          "of millions, and it is the entire defence.",
          "",
          "This application uses bcrypt at a work factor of 10 — around 100 ms per hash, slow",
          "enough to make offline cracking uneconomic and fast enough for an interactive login.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Salt, and what it actually prevents",
        body: [
          "A **salt** is a unique random value per password, stored in the clear alongside the",
          "hash. It is not secret, and it does not need to be.",
          "",
          "What it prevents is *amortisation*. Without a salt, identical passwords produce",
          "identical hashes, and three things follow:",
          "",
          "1. A precomputed table (a rainbow table) covers your whole database at once.",
          "2. One cracking run breaks every account sharing that password.",
          "3. Equal hashes reveal which users chose the same password — visible in the table,",
          "   before any cracking at all.",
          "",
          "With a unique salt per row, the attacker must run a separate campaign per user. The",
          "cost stops being per-database and becomes per-account.",
          "",
          "A **pepper** is a different thing: a single secret value, shared across all rows, kept",
          "outside the database (in configuration or a key manager). If the database leaks but the",
          "configuration does not, the hashes are unusable. It is genuine defence in depth, and it",
          "brings an operational cost — rotating a pepper means rehashing on next login, so plan",
          "for it before adopting it.",
          "",
          "Note that bcrypt, scrypt and Argon2 all generate and embed the salt for you. If you are",
          "writing salt-handling code by hand, check whether your library already did it.",
        ].join("\n"),
        diagram: {
          title: "Why the same password must not hash the same way",
          frames: [
            {
              label: "Unsalted: shared work",
              caption:
                "Two users chose the same password. Identical hashes, so one cracking run breaks both -- and the table itself reveals that they match.",
              code: "ada  -> 5e88...\nbo   -> 5e88...   <- same password, visible",
            },
            {
              label: "Precomputation wins",
              caption:
                "A table of common passwords to digests is built once and reused against every database in the world.",
              code: 'lookup["5e88..."] -> "password1"',
            },
            {
              label: "Salted: per-account work",
              caption:
                "A unique random salt per row makes the digests differ. The precomputed table is worthless and each account must be attacked separately.",
              code: "ada  -> salt_a + hash(salt_a, pw) -> 91af...\nbo   -> salt_b + hash(salt_b, pw) -> c703...",
            },
            {
              label: "Slow by design",
              caption:
                "Salt removes the shortcut; cost parameters make each remaining guess expensive. You need both -- salt alone still allows billions of guesses per second.",
              code: "bcrypt cost 10  ~=  100 ms per guess",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Feel the cost of iteration count",
        language: "javascript",
        goal:
          "Derive a key from a password with PBKDF2 at several iteration counts and measure how the elapsed time scales.",
        hint:
          "`crypto.subtle.deriveBits` with `{ name: 'PBKDF2', salt, iterations, hash: 'SHA-256' }`. Time it with `Date.now()` around the await.",
        starterCode: [
          "const enc = new TextEncoder();",
          "const password = 'correct horse battery staple';",
          "",
          "// A per-password random salt. Stored in the clear next to the hash.",
          "const salt = crypto.getRandomValues(new Uint8Array(16));",
          "",
          "const baseKey = await crypto.subtle.importKey(",
          "  'raw', enc.encode(password), 'PBKDF2', false, ['deriveBits'],",
          ");",
          "",
          "async function timeDerive(iterations) {",
          "  const started = Date.now();",
          "  await crypto.subtle.deriveBits(",
          "    { name: 'PBKDF2', salt, iterations, hash: 'SHA-256' },",
          "    baseKey,",
          "    256,",
          "  );",
          "  return Date.now() - started;",
          "}",
          "",
          "for (const n of [1000, 10000, 100000]) {",
          "  console.log(n, 'iterations ->', await timeDerive(n), 'ms');",
          "}",
          "",
          "// TODO: roughly how does the time scale with the iteration count?",
          "// TODO: at 1 ms per guess, how many guesses can an attacker make per hour",
          "//       on one core? Compare that with a wordlist of 10 million entries.",
          "// TODO: change the salt and derive again with the same password.",
          "//       Do you get the same bits?",
        ].join("\n"),
        body: [
          "The scaling is linear, and that linearity is the whole design: the parameter is a dial",
          "you turn as hardware improves, without changing anything else.",
          "",
          "Do the arithmetic in the second question properly. It is the argument you will need",
          "when someone proposes SHA-256 \"because it is fast\".",
          "",
          "PBKDF2 is used here because `crypto.subtle` provides it. It is the weakest of the",
          "acceptable options — it resists raw speed but not custom hardware, because it needs",
          "almost no memory. Argon2id and scrypt deliberately require memory as well, which is",
          "what makes a GPU or ASIC farm expensive rather than merely fast. For a new server-side",
          "system, prefer Argon2id; for this one, bcrypt was already the established choice.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Is the salt a secret?",
        prompt: "Where should a password's salt be stored?",
        options: [
          {
            text: "In the clear, next to the hash — it stops precomputation and shared cracking work, which does not require it to be secret",
            correct: true,
          },
          { text: "In application configuration, so a database leak does not expose it" },
          { text: "Nowhere — it can be derived from the user's email address" },
          { text: "Encrypted in a separate table, since it is as sensitive as the hash" },
        ],
        explanation:
          "The salt must be available at login to recompute the hash, and its job is only to make each row's work unique — which it does whether or not the attacker knows it. That is why bcrypt embeds the salt directly in its own output string. The second option describes a pepper, which is a genuinely secret site-wide value and a useful additional layer, but it is a different mechanism and not a substitute. Deriving a salt from the email fails on both counts: it is predictable, so it can be precomputed, and it changes when the user changes their address.",
        body: "A question that separates 'I know the word salt' from 'I know what it does'.",
      },
      {
        kind: "explain",
        title: "The login endpoint's other obligations",
        body: [
          "Correct storage is necessary and not sufficient. Four things the endpoint itself owes.",
          "",
          "**Do not reveal whether an account exists.** \"No such user\" and \"wrong password\" as",
          "distinct messages turn your login form into a membership oracle. One message for both.",
          "And watch the *timing*: if a missing user returns immediately while a real one waits",
          "100 ms for bcrypt, the timing leaks what the message did not. Hash a dummy value on",
          "the miss path so both take comparable time. This application's password-reset endpoint",
          "documents exactly this requirement.",
          "",
          "**Rate-limit, per account and per source.** A slow hash makes offline cracking",
          "expensive; it does nothing about someone trying the ten most common passwords against",
          "every account you have. That is a rate-limiting problem, not a hashing one.",
          "",
          "**Rehash on successful login when parameters change.** You verified with the old cost",
          "factor and you are holding the plaintext password for exactly this one moment — the",
          "only moment you can upgrade. Take it.",
          "",
          "**Never log the password.** Not on error, not in a request dump, not in the \"just for",
          "debugging\" branch. Logs are copied, shipped to third parties and retained far longer",
          "than anyone intends, and they are almost never protected like a password table.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "crypto-symmetric-encryption-and-modes",
    track: "cryptography",
    title: "Symmetric Encryption and Why Mode Matters",
    summary:
      "AES is not the decision. The mode, the nonce and whether the ciphertext is authenticated are the decisions, and each has a failure you can see.",
    level: "intermediate",
    estimatedMinutes: 45,
    refs: [
      "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt",
      "https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues",
    ],
    steps: [
      {
        kind: "explain",
        title: "A block cipher is not an encryption scheme",
        body: [
          "AES encrypts exactly 16 bytes with a key. That is all it does. Everything else — how",
          "you handle a message that is not 16 bytes, how you avoid revealing that two blocks are",
          "identical, how you detect tampering — is the **mode of operation**, and the mode is",
          "where schemes succeed or fail.",
          "",
          "**ECB** encrypts each block independently. Deterministic, so identical plaintext blocks",
          "produce identical ciphertext blocks, and the structure of your data survives encryption",
          "in plain view. This is the classic failure, and the next step lets you see it.",
          "",
          "**CBC** chains each block into the next and starts from a random initialisation vector,",
          "so the same message encrypts differently every time. It hides structure. It does not",
          "detect tampering — an attacker who flips ciphertext bits changes the plaintext in ways",
          "CBC cannot notice, which is what padding-oracle attacks build on.",
          "",
          "**GCM** is CBC's structural hiding plus an authentication tag: decryption *fails* if",
          "anything was altered. It is authenticated encryption, and it is what you should reach",
          "for.",
          "",
          "The rule to leave with: **use AES-GCM**. Encryption without authentication is a bug in",
          "almost every real setting, because \"the attacker can change the message and you will",
          "not notice\" is rarely acceptable.",
        ].join("\n"),
        diagram: {
          title: "Three modes, three outcomes",
          frames: [
            {
              label: "ECB: structure survives",
              caption:
                "Each block encrypted independently, so equal plaintext blocks give equal ciphertext blocks. Repetition in the data is repetition in the output.",
              code: "AAAA AAAA BBBB  ->  7f3c 7f3c 91ad",
            },
            {
              label: "CBC: structure hidden",
              caption:
                "Each block is mixed with the previous one, starting from a random IV. The same message encrypts differently every time.",
              code: "IV + chain  ->  a19c 44e0 be71   (different each run)",
            },
            {
              label: "CBC: tampering undetected",
              caption:
                "Flip ciphertext bits and decryption still produces bytes. There is no integrity check, so nothing rejects the altered message.",
              code: "ciphertext[5] ^= 1  ->  decrypts to different plaintext, no error",
            },
            {
              label: "GCM: tampering rejected",
              caption:
                "An authentication tag covers the ciphertext. Any alteration makes decrypt() throw rather than return plausible garbage. This is the one to use.",
              code: "decrypt(tampered)  ->  OperationError",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "See ECB patterning",
        language: "javascript",
        goal:
          "Encrypt a highly repetitive message with a deterministic block-by-block scheme, and observe the repetition surviving into the ciphertext.",
        notProductionReady: true,
        hint:
          "Encrypt each 16-byte block separately with AES-CBC and a fixed all-zero IV. That reproduces ECB's behaviour block by block — which is exactly the point being demonstrated.",
        starterCode: [
          "// TEACHING CODE. This deliberately builds a BROKEN construction so you can",
          "// see the failure. Never do this in real software: SubtleCrypto does not",
          "// offer ECB precisely because it should not be used.",
          "",
          "const key = await crypto.subtle.generateKey(",
          "  { name: 'AES-CBC', length: 256 }, false, ['encrypt'],",
          ");",
          "",
          "const zeroIv = new Uint8Array(16);   // fixed IV == the bug, on purpose",
          "",
          "async function encryptBlockEcbStyle(block16) {",
          "  const out = await crypto.subtle.encrypt(",
          "    { name: 'AES-CBC', iv: zeroIv }, key, block16,",
          "  );",
          "  // Take only the first 16 bytes: the rest is CBC padding.",
          "  return [...new Uint8Array(out).slice(0, 16)]",
          "    .map((b) => b.toString(16).padStart(2, '0')).join('');",
          "}",
          "",
          "// A repetitive message: three identical blocks, then a different one.",
          "const enc = new TextEncoder();",
          "const blocks = [",
          "  enc.encode('AAAAAAAAAAAAAAAA'),",
          "  enc.encode('AAAAAAAAAAAAAAAA'),",
          "  enc.encode('AAAAAAAAAAAAAAAA'),",
          "  enc.encode('BBBBBBBBBBBBBBBB'),",
          "];",
          "",
          "for (const b of blocks) console.log(await encryptBlockEcbStyle(b));",
          "",
          "// TODO: how many DISTINCT ciphertext blocks did you get from four inputs?",
          "// TODO: what would this look like for a bitmap image of a logo?",
          "// TODO: now encrypt the whole 64-byte message ONCE with AES-CBC and a",
          "//       random IV, and check whether any repetition is visible.",
        ].join("\n"),
        body: [
          "Four inputs, two distinct outputs. The repetition in the plaintext is right there in",
          "the ciphertext, and an attacker who never recovers the key still learns the shape of",
          "your data — which for structured records (a fixed-format field, a repeated header, an",
          "image with flat colour) is often enough.",
          "",
          "The famous demonstration of this is an image encrypted with ECB: the outline remains",
          "clearly visible. Nothing about AES failed; the mode leaked the structure.",
          "",
          "Then do the last TODO. One `encrypt` call with a random IV, and the repetition is gone.",
          "The primitive was the same both times.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "The nonce rule, and what breaks when you break it",
        body: [
          "GCM needs a **nonce** (an IV) per message. One rule governs it, and it is absolute:",
          "**never reuse a nonce with the same key.**",
          "",
          "GCM is a stream construction: it turns the key and nonce into a keystream and XORs that",
          "over the plaintext. Encrypt two messages with the same key and nonce and both used the",
          "same keystream, so XORing the two ciphertexts together cancels the keystream entirely",
          "and leaves the two plaintexts XORed with each other. No key needed. With any guess",
          "about one message, the other falls out.",
          "",
          "Worse, nonce reuse in GCM leaks material that lets an attacker **forge** authentication",
          "tags — so the integrity guarantee goes too, not just the confidentiality.",
          "",
          "In practice:",
          "",
          "- Generate it with `crypto.getRandomValues(new Uint8Array(12))`, fresh per message.",
          "  12 bytes is GCM's standard size and what the construction is optimised for.",
          "- Store or transmit it next to the ciphertext. **It is not secret** — only unique.",
          "- Never derive it from something that repeats: a user id, a counter that resets, a",
          "  timestamp in seconds. A hard-coded IV is the same bug with no ambiguity.",
          "- If you are encrypting enough messages under one key to worry about random collisions,",
          "  the answer is to rotate the key, not to get cleverer about the nonce.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "AES-GCM, and tampering that gets caught",
        language: "javascript",
        goal:
          "Encrypt and decrypt with AES-GCM using a fresh random IV, then flip one ciphertext byte and confirm decryption refuses rather than returning wrong plaintext.",
        hint:
          "Wrap the tampered `decrypt` in try/catch — it rejects with an OperationError, and catching it is how you observe the authentication working.",
        starterCode: [
          "const enc = new TextEncoder();",
          "const dec = new TextDecoder();",
          "",
          "const key = await crypto.subtle.generateKey(",
          "  { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt'],",
          ");",
          "",
          "const message = 'transfer 100 to account 7';",
          "",
          "// Fresh, random, 12 bytes, one per message. Not secret; must be unique.",
          "const iv = crypto.getRandomValues(new Uint8Array(12));",
          "",
          "const ciphertext = new Uint8Array(",
          "  await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(message)),",
          ");",
          "",
          "const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ciphertext);",
          "console.log('round trip:', dec.decode(plain));",
          "",
          "// TODO: flip one bit of the ciphertext and try to decrypt it in a try/catch.",
          "//       What happens, and how is that different from CBC?",
          "",
          "// TODO: encrypt the SAME message again with a NEW random iv.",
          "//       Compare the two ciphertexts.",
          "",
          "// TODO: try to decrypt with the wrong iv but the right key.",
        ].join("\n"),
        body: [
          "Three results worth stating plainly.",
          "",
          "Tampering makes `decrypt` **reject**. It does not return altered plaintext for your code",
          "to act on. That is the difference authentication makes, and it is why unauthenticated",
          "modes are the wrong default.",
          "",
          "The same message under a new IV gives a completely different ciphertext. An observer",
          "cannot tell you sent the same thing twice.",
          "",
          "The wrong IV fails the tag check, so it fails the same way tampering does — the IV is",
          "part of what is authenticated. Which is why it must travel with the ciphertext, and why",
          "losing it means losing the data.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Reusing a GCM nonce",
        prompt:
          "You encrypt two different messages with AES-GCM using the same key and the same 12-byte IV. What is the consequence?",
        options: [
          {
            text: "XORing the two ciphertexts reveals the two plaintexts XORed together, with no key needed — and tag forgery becomes possible",
            correct: true,
          },
          { text: "Nothing; the IV only needs to be unpredictable, and it still is" },
          { text: "The second encryption fails, because SubtleCrypto detects the reuse" },
          { text: "Only the second message is weakened; the first stays secure" },
        ],
        explanation:
          "GCM derives a keystream from the key and nonce and XORs it over the plaintext, so the same pair produces the same keystream. Two ciphertexts sharing a keystream cancel it when XORed together, leaving plaintext XORed with plaintext — recoverable with any partial knowledge of either. Both messages are affected, not just the second. The reuse also exposes the authentication subkey material, so an attacker can forge valid tags. Nothing in the API prevents this: uniqueness is entirely the caller's responsibility, which is why 'generate it randomly, every message' is the only safe habit.",
        body: "The single most consequential rule in this module. It is worth being able to explain, not just obey.",
      },
    ],
  },
];
