// =============================================================================
// CYBERSECURITY TRACK — three modules. DEFENSIVE AND SANDBOXED ONLY.
// -----------------------------------------------------------------------------
// docs/research/CURRICULUM_PLAN.md had not reached this track when this content was
// authored (the published file covers `oop` and `dbms` and is marked CHUNK-2), so
// the ladder here is this stream's own outline, following the plan's `sec-` slug
// convention and the plan's own constraint note for the track.
//
// THE NON-NEGOTIABLE RULE, AND HOW IT IS APPLIED HERE.
//
// Every module teaches how to BUILD something that holds up, never how to attack
// anything. Concretely, what is in scope and what is not:
//
//   IN:  input validation and allow-listing; parameterised queries; output
//        encoding per context; password storage; authorization modelling
//        (including object-level checks); secure response headers; the reasoning
//        behind each control.
//   OUT: any operational exploitation. No scanning, no enumeration tooling, no
//        credential attacks, no payload collections, no third-party or real
//        targets of any kind. Where a lab shows a failure, it fails against a
//        fixture created inside the lab itself, in a Web Worker with no DOM, no
//        cookies, no session and no network — or against an in-memory SQLite
//        database created by the same lab.
//
// One deliberate exclusion is recorded in `sec-output-encoding` below: the XSS
// module demonstrates encoding as string logic rather than by rendering a payload
// into a live sandboxed iframe. The reason is stated in that module's prose and in
// this stream's report — the sandboxed-iframe editor belongs to another stream's
// files, and the encoding decision (which characters, in which context) is
// completely observable without rendering anything.
// =============================================================================

import type { SeedModule } from "./types";

export const cybersecurityModules: SeedModule[] = [
  // -------------------------------------------------------------------------
  {
    slug: "sec-input-validation",
    track: "cybersecurity",
    title: "Validating Input at the Boundary",
    summary:
      "Every value that came from outside your program is a claim, not a fact. Validation is where you decide what claims you are willing to act on.",
    level: "beginner",
    estimatedMinutes: 40,
    refs: [
      "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html",
      "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html",
    ],
    steps: [
      {
        kind: "explain",
        title: "Allow-list, never deny-list",
        body: [
          "There are two ways to validate. One works.",
          "",
          "A **deny-list** enumerates what is forbidden: strip `<script>`, reject `../`, remove",
          "quotes. It fails because you have to be right about every case, forever, and the",
          "attacker only has to find one you missed. `<ScRiPt>`, `<img onerror=...>`,",
          "URL-encoded `..%2f`, a Unicode form that normalises into the thing you filtered.",
          "Each patch is a new special case and the list never converges.",
          "",
          "An **allow-list** states what is acceptable and rejects the rest: this field is 1–3",
          "digits, in the range 0–100; this one matches a strict email pattern; this one is one",
          "of exactly four strings. Anything unrecognised is refused — including inputs nobody",
          "anticipated, which is the whole point.",
          "",
          "Two disciplines go with it.",
          "",
          "**Validate at the boundary, once, and convert.** Parse the string into the typed value",
          "the rest of your code wants, so a validated number is a number and not a string that",
          "has been inspected. If the type is still `string`, later code cannot tell validated",
          "from raw and will re-check or forget to.",
          "",
          "**Reject; do not repair.** Silently stripping characters turns an invalid input into a",
          "different valid one, and the caller never learns their request was altered. Sanitising",
          "for *output* is a real technique and belongs in the next module; sanitising for input",
          "is usually a deny-list with better manners.",
        ].join("\n"),
        diagram: {
          title: "Two strategies, one that converges",
          frames: [
            {
              label: "Deny-list: patch by patch",
              caption:
                "Each rule blocks one known form. The rule set grows with every case someone thinks of, and never finishes.",
              code: 'value.replace("<script>", "")',
            },
            {
              label: "Deny-list: the case you missed",
              caption:
                "Different casing, a different tag, an encoded form -- any one of these walks past the filter, and the filter reported success.",
              code: '"<ScRiPt>", "<img onerror=...>", "..%2fetc"',
            },
            {
              label: "Allow-list: state what is valid",
              caption:
                "One rule describes acceptable input. Everything else is refused, including forms nobody predicted.",
              code: "/^[0-9]{1,3}$/  and  0 <= n <= 100",
            },
            {
              label: "Parse, do not merely check",
              caption:
                "Return the typed value, so downstream code holds a number rather than a string somebody once looked at. The type now carries the guarantee.",
              code: "parseScore(raw) -> { ok: true, value: 88 }",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Write a parsing validator",
        language: "javascript",
        goal:
          "Write parseScore so it returns a typed result for valid input and a reason for everything else, then check it against the awkward cases.",
        hint:
          "`Number('')` is 0 and `Number(' 12 ')` is 12 — so test the STRING shape with a regular expression first, and only then convert.",
        starterCode: [
          "// Return { ok: true, value: <number> } or { ok: false, reason: <string> }.",
          "// Accept: a string of 1-3 digits whose numeric value is 0..100.",
          "// Reject everything else, and say why.",
          "",
          "function parseScore(raw) {",
          "  // TODO: reject non-strings",
          "  // TODO: reject anything not matching /^[0-9]{1,3}$/",
          "  // TODO: convert, then reject out-of-range",
          "  // TODO: return the typed value",
          "}",
          "",
          "const cases = [",
          "  '88', '0', '100',          // valid",
          "  '101', '-1', '1e2',        // out of range or not plain digits",
          "  ' 88', '88 ', '', '  ',    // whitespace",
          "  '08', '+88', '88.0',       // surprising but plausible",
          "  null, undefined, 88,       // not even strings",
          "  '٨٨',                       // Arabic-Indic digits",
          "];",
          "",
          "for (const c of cases) {",
          "  console.log(JSON.stringify(c), '->', JSON.stringify(parseScore(c)));",
          "}",
        ].join("\n"),
        body: [
          "The interesting rows are the last few.",
          "",
          "`'1e2'` is 100 to `Number` and is not a plain digit string. Which do you want? Decide",
          "deliberately rather than inheriting whatever `Number` does.",
          "",
          "`88` as an actual number arrives when a JSON body carried a number rather than a",
          "string. Your validator must handle it — either accept it explicitly or reject it",
          "clearly, never crash on `.match` of a non-string.",
          "",
          "`'٨٨'` is eighty-eight in Arabic-Indic digits. `/^[0-9]{1,3}$/` refuses it and `/^\\d+$/`",
          "in some engines does not, because `\\d` can be Unicode-aware. If your users legitimately",
          "type those digits, the right answer is to normalise on purpose — not to discover the",
          "difference from a bug report.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Data confused with code",
        body: [
          "Injection is one bug wearing many hats. In every case, a value that was *data* got",
          "parsed as *instructions*, because it was pasted into a string that a parser then read.",
          "",
          "```js",
          "// SQL: the value becomes part of the statement",
          "\"SELECT * FROM students WHERE email = '\" + input + \"'\"",
          "",
          "// Shell: the value becomes part of the command line",
          "`convert ${filename} out.png`",
          "",
          "// HTML: the value becomes part of the document",
          "element.innerHTML = 'Hello ' + name;",
          "```",
          "",
          "Same shape, three parsers. The defence is also the same shape, and it is not escaping.",
          "",
          "**Keep the data out of the string.** Send the query and the values on separate",
          "channels, so the parser sees a placeholder where the value goes and can never treat",
          "the value as syntax. That is a parameterised query, an `execFile` with an argument",
          "array, `textContent` instead of `innerHTML`.",
          "",
          "Escaping is the fallback, not the plan. It requires knowing the target parser's rules",
          "exactly, applying them in the right order, and never double-applying them. Separation",
          "requires none of that, because there is no ambiguity to resolve.",
          "",
          "Where separation is genuinely unavailable — a table name, a sort column, an ORDER BY",
          "direction — the answer is an **allow-list mapping** from a small set of accepted inputs",
          "to a small set of literal strings you wrote. Never the user's text, however well",
          "checked.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Concatenation versus binding, in one database",
        language: "sql",
        setup: [
          "CREATE TABLE students (",
          "  id    INTEGER PRIMARY KEY,",
          "  name  TEXT NOT NULL,",
          "  email TEXT NOT NULL UNIQUE",
          ");",
          "INSERT INTO students (id, name, email) VALUES",
          "  (1, 'Ada Nwosu', 'ada@example.test'),",
          "  (2, 'Bo Chen',   'bo@example.test'),",
          "  (3, 'Cy Okafor', 'cy@example.test');",
        ].join("\n"),
        goal:
          "Run the statement that string concatenation would have produced, see that it returns every row, then write the version where the value cannot be syntax.",
        hint:
          "The concatenated statement below is already assembled for you — read it and work out why the WHERE clause is always true.",
        starterCode: [
          "-- SANDBOX. This database is created by this lab, lives in memory in a",
          "-- Web Worker, and is destroyed when the run ends. It is our own fixture.",
          "-- The point is to see what a bug looks like from the inside, so you can",
          "-- recognise it in review. Never aim this at a system you do not own.",
          "",
          "-- 1. The intended query: one student by email.",
          "SELECT * FROM students WHERE email = 'ada@example.test';",
          "",
          "-- 2. Now the statement that",
          "--      \"... WHERE email = '\" + input + \"'\"",
          "--    produces when input is:  ' OR '1'='1",
          "--    Read it before running. Which part is data and which is syntax?",
          "SELECT * FROM students WHERE email = '' OR '1'='1';",
          "",
          "-- 3. Why did that return three rows rather than zero?",
          "--    Write the answer as a comment.",
          "",
          "-- 4. Now the safe form. In application code the value travels separately",
          "--    from the statement text, so the parser sees a placeholder:",
          "--      db.query('SELECT * FROM students WHERE email = $1', [input])",
          "--    Write the SELECT you would want with the literal value quoted",
          "--    correctly, and confirm a quote inside the value stays data:",
          "SELECT * FROM students WHERE email = 'o''brien@example.test';",
          "",
          "-- 5. Escaping is not a complete answer. Name one thing binding cannot",
          "--    protect (hint: what appears after ORDER BY?) and say what does.",
        ].join("\n"),
        body: [
          "Step 3's answer: the quote in the input closed the string literal, so `OR '1'='1'`",
          "stopped being part of the value and became part of the condition. The parser did",
          "exactly what it was told. Nothing malfunctioned.",
          "",
          "Step 5's answer: a bound parameter is always a *value*, so it cannot be a table name,",
          "a column name, or a sort direction. Those need an allow-list mapping — `{ name:",
          "'s.name', score: 'e.score' }` — where the user picks a key and your code supplies the",
          "literal.",
          "",
          "And the wider point: parameterised queries remove this entire class. Not \"reduce the",
          "risk of\" — remove. There is no residual cleverness required, which is why it is the",
          "single highest-value habit in this track.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Is escaping quotes enough?",
        prompt:
          "Your code doubles every single quote in user input before concatenating it into SQL. Is that a complete defence against injection?",
        options: [
          {
            text: "No — it depends on getting every context and encoding right, and it does nothing for values that are not string literals",
            correct: true,
          },
          { text: "Yes, provided every quote is escaped correctly without exception" },
          { text: "Yes for SELECT statements; no for INSERT and UPDATE" },
          { text: "No, because escaping makes the query too slow to be practical" },
        ],
        explanation:
          "Escaping can be done correctly, and it is still the wrong plan. It is per-context: a numeric field concatenated without quotes takes no quote to attack, and a value going into a LIKE pattern or an identifier has different rules again. It is order-dependent, so a value escaped then decoded elsewhere is unescaped again. And it protects only string literals — a sort column or table name interpolated from input is untouched by any quote handling. Parameter binding removes the ambiguity instead of managing it, and an allow-list mapping covers the identifiers binding cannot.",
        body: "The answer that matters is the reason, not the yes/no.",
      },
      {
        kind: "explain",
        title: "Validation is not authorization",
        body: [
          "A distinction worth being ruthless about, because conflating the two produces the most",
          "common serious bug in web applications.",
          "",
          "**Validation** asks: is this input well formed? `studentId=7` — yes, that is a positive",
          "integer.",
          "",
          "**Authorization** asks: is *this caller* allowed to do this, to *this object*? Is the",
          "signed-in user student 7, or someone entitled to read student 7's data?",
          "",
          "A perfectly valid `studentId=7` from user 12 is an authorization failure, and no amount",
          "of validation detects it. This is why an endpoint that reads its subject from a",
          "parameter is a different thing from one that reads it from the session — and why the",
          "progress endpoint in this application takes no `studentId` at all, documenting that",
          "accepting one \"would turn a self-service endpoint into a read of any classmate's",
          "grades\". The safest check is the one that cannot be got wrong because the input does",
          "not exist.",
          "",
          "Two more things validation does not do.",
          "",
          "**It is not authentication.** A well-formed token is not a valid token.",
          "",
          "**It is not output encoding.** A validated string can still break the HTML it lands in,",
          "because whether a character is dangerous depends on where it is going, not where it came",
          "from. That is the next module.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "sec-output-encoding",
    track: "cybersecurity",
    title: "Output Encoding and XSS Defence",
    summary:
      "A string is dangerous because of where it is going, not where it came from. Encode for the destination, and prefer APIs that cannot interpret markup at all.",
    level: "beginner",
    estimatedMinutes: 40,
    refs: [
      "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
      "https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent",
    ],
    steps: [
      {
        kind: "explain",
        title: "The destination decides what is dangerous",
        body: [
          "Cross-site scripting happens when a value you inserted into a page is parsed as markup",
          "or script rather than displayed as text. The value is not intrinsically dangerous —",
          "`<b>` is fine in a JSON response, fatal in an HTML body, and irrelevant in a CSS",
          "declaration. **The destination decides.**",
          "",
          "Which means \"sanitise on input\" cannot work: at the point of input you do not know",
          "where the value will end up, and one value often ends up in several places. Encode at",
          "the point of output, for that specific context.",
          "",
          "Four contexts, four different rule sets:",
          "",
          "**HTML text.** `&`, `<`, `>` must become entities. Otherwise `<script>` opens a tag.",
          "",
          "**An attribute value.** Quotes matter too — `\"` and `'` — because breaking out of the",
          "attribute lets the attacker add another one, such as `onerror`. Always quote your",
          "attributes; an unquoted attribute can be escaped with a space alone.",
          "",
          "**Inside a `<script>` block.** HTML entities do not help; the JavaScript parser does not",
          "decode them. This context needs JavaScript string escaping, and the string `</script>`",
          "anywhere inside terminates the block regardless.",
          "",
          "**A URL.** `javascript:` as a scheme is executable. Percent-encoding the parameters does",
          "nothing about the scheme, so the scheme needs its own allow-list — `https:`, `mailto:`,",
          "and a small set you chose.",
          "",
          "The practical conclusion: get out of the encoding business where you can. `textContent`",
          "cannot create an element. React's `{value}` escapes for you. Both are correct by",
          "construction, which is worth more than any escaping function you write.",
        ].join("\n"),
        diagram: {
          title: "One value, four destinations",
          frames: [
            {
              label: "HTML text",
              caption:
                "Angle brackets start a tag, so they must become entities. This is the context people think of as 'the' XSS context.",
              code: "&lt;b&gt;hi&lt;/b&gt;   shown as text, not parsed",
            },
            {
              label: "Attribute value",
              caption:
                "Quotes end the attribute, letting the attacker add another one. Encode quotes too, and always quote the attribute in the first place.",
              code: 'title="he said &quot;hi&quot;"',
            },
            {
              label: "Inside a script block",
              caption:
                "The JavaScript parser does not decode HTML entities, so entity encoding is no defence here. And the literal text closing the script tag ends the block wherever it appears.",
              code: 'const s = "\\u003c/script\\u003e";',
            },
            {
              label: "URL",
              caption:
                "Percent-encoding the query string does nothing about an executable scheme. The scheme needs an allow-list of its own.",
              code: 'href="javascript:..."   -> reject the scheme',
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Encode for HTML text and for an attribute",
        language: "javascript",
        goal:
          "Write two encoders — one for HTML text, one for an attribute value — and check them against inputs that break the weaker one.",
        hint:
          "Replace `&` FIRST. Doing it after the others would double-encode the ampersands your own replacements just introduced.",
        starterCode: [
          "// No DOM here: this worker has no document, so nothing below can render.",
          "// That is deliberate. The DECISION -- which characters, in which context --",
          "// is entirely visible as string output, and that decision is the lesson.",
          "",
          "function encodeHtmlText(value) {",
          "  // TODO: & < >   (ampersand first!)",
          "}",
          "",
          "function encodeHtmlAttribute(value) {",
          "  // TODO: & < > and BOTH quote characters",
          "}",
          "",
          "const inputs = [",
          "  'Ada & Bo',",
          "  '<b>bold</b>',",
          "  '<img src=x onerror=alert(1)>',",
          '  \'" onmouseover="steal()\',',
          "  \"' onfocus='steal()\",",
          "  'already &amp; encoded',",
          "];",
          "",
          "for (const input of inputs) {",
          "  console.log('text: ', encodeHtmlText(input));",
          "  console.log('attr: ', encodeHtmlAttribute(input));",
          "  console.log('---');",
          "}",
          "",
          "// TODO: which input is safe from encodeHtmlText but NOT from it when the",
          "//       result is placed inside an unquoted attribute?",
          "// TODO: what does 'already &amp; encoded' become? Is that a bug?",
        ].join("\n"),
        body: [
          "Two conclusions to take away.",
          "",
          "The quote payloads are harmless in HTML text and dangerous in an attribute. That is the",
          "context-dependence, demonstrated: the same encoder is sufficient in one place and",
          "insufficient in another.",
          "",
          "`already &amp; encoded` becomes `already &amp;amp; encoded`. **Double encoding is a real",
          "bug**, and it is the reason encoding belongs at the output boundary and nowhere else. If",
          "two layers each encode \"to be safe\", users see `&amp;` in their own names, and the",
          "usual fix — decoding first — reopens the hole you were closing.",
          "",
          "Encode once, at the edge, for the destination.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "The API you choose matters more than the encoder you write",
        body: [
          "Encoders are a fallback. The stronger move is to use an interface that cannot interpret",
          "markup, so there is nothing to encode.",
          "",
          "**`textContent`, not `innerHTML`.** `textContent` sets text. It cannot create an",
          "element, so no input can become a tag. The same applies to `createTextNode` and to",
          "`setAttribute` over building an attribute string by hand.",
          "",
          "**A framework's default interpolation.** React's `{value}`, Vue's `{{ value }}` and",
          "similar escape automatically. The dangerous forms are opt-in and loudly named —",
          "`dangerouslySetInnerHTML`, `v-html` — which is good design: the risk is visible in review",
          "rather than implied by the absence of a call. This repository's own markdown renderer",
          "makes the same choice, deliberately omitting the plugin that would allow raw HTML",
          "through.",
          "",
          "**A vetted sanitiser when you genuinely must accept HTML.** Rich-text input is a real",
          "requirement, and the answer is a maintained library with an allow-list of tags and",
          "attributes — never a regular expression. HTML parsing is not a regular language, and",
          "every hand-rolled tag stripper has been bypassed.",
          "",
          "**Content-Security-Policy as the layer underneath.** A policy that forbids inline script",
          "and restricts script sources means an injected `<script>` does not execute even if one",
          "gets through. It is defence in depth: it does not excuse a missing encoder, it limits",
          "what a missed one costs.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Where does encoding belong?",
        prompt:
          "A comment body will be shown in an HTML page, sent in a JSON API response, and included in a plain-text email. Where should it be encoded?",
        options: [
          {
            text: "At each output point, encoded for that destination — stored raw, because the storage layer cannot know where it will go",
            correct: true,
          },
          { text: "Once on input, before storing, so every consumer is safe by default" },
          { text: "Once on input and again on output, for defence in depth" },
          { text: "Only in the HTML case; JSON and plain text cannot be attacked" },
        ],
        explanation:
          "HTML-encoding on the way in corrupts the other two outputs — the JSON consumer receives `&amp;` where the user typed `&`, and the email shows entities as literal text. Encoding twice produces exactly that double-encoding bug. Store the value as the user typed it, and encode at each boundary for the parser on the other side of it. The last option is wrong about JSON too: a value interpolated into a JavaScript context, or a JSON response served with the wrong content type, has its own escaping requirements.",
        body: "The wrong answer here is the one most often chosen, and it is chosen for good-sounding reasons.",
      },
      {
        kind: "explain",
        title: "Secure response headers, and what each one actually stops",
        body: [
          "Headers are cheap and each one closes a specific hole. Worth knowing what, precisely.",
          "",
          "**`Content-Security-Policy`** restricts where scripts, styles and frames may come from.",
          "A policy without `unsafe-inline` is what turns an injected `<script>` into inert text.",
          "It is the highest-value header and the fiddliest to adopt, because it requires knowing",
          "what your page actually loads.",
          "",
          "**`X-Content-Type-Options: nosniff`** stops the browser second-guessing your",
          "`Content-Type`. Without it, an uploaded file served as `text/plain` can be sniffed as",
          "HTML and executed in your origin.",
          "",
          "**`Strict-Transport-Security`** makes the browser refuse plain HTTP to your host for a",
          "declared period, closing the window a redirect leaves open.",
          "",
          "**`X-Frame-Options` / CSP `frame-ancestors`** stops your page being framed by someone",
          "else's, which is what clickjacking needs. Note the inverse, recorded in this",
          "repository's own decisions: W3Schools sends this header, so its pages cannot be embedded",
          "here — which is why those references are outbound links.",
          "",
          "**`Referrer-Policy`** limits how much of your URL leaks to third parties. If your URLs",
          "contain identifiers or tokens, this matters more than it sounds.",
          "",
          "**Cookie attributes** are the same category: `HttpOnly` keeps a session cookie out of",
          "reach of any injected JavaScript, `Secure` keeps it off plain HTTP, and `SameSite`",
          "limits cross-site sending. `HttpOnly` in particular is what makes an XSS bug expensive",
          "for the attacker rather than immediately fatal for the session.",
          "",
          "None of these is a substitute for encoding. All of them decide how much a single missed",
          "encoder costs.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "sec-authorization-modelling",
    track: "cybersecurity",
    title: "Modelling Authorization",
    summary:
      "Authorization is a data model, not a scatter of if-statements. The failure that matters most is not the missing role check but the missing object check.",
    level: "intermediate",
    estimatedMinutes: 45,
    refs: [
      "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",
      "https://cheatsheetseries.owasp.org/cheatsheets/Access_Control_Cheat_Sheet.html",
    ],
    steps: [
      {
        kind: "explain",
        title: "Two questions, and the one people forget",
        body: [
          "Every protected operation asks two things:",
          "",
          "1. **May this kind of user do this kind of thing?** May an instructor grade?",
          "2. **May this specific user do it to this specific object?** May instructor 4 grade",
          "   submission 91?",
          "",
          "The first is a role check and almost everybody writes it. The second is an",
          "**object-level** check, and its absence is consistently among the most common serious",
          "vulnerabilities in web applications.",
          "",
          "The shape of the bug:",
          "",
          "```js",
          "// Role checked. Object not.",
          "if (user.role !== 'instructor') return forbid();",
          "const submission = await db.findSubmission(req.params.id);   // any id",
          "return render(submission);",
          "```",
          "",
          "Any instructor can read any submission by changing a number in the URL. Nothing is",
          "malformed, nothing is unauthenticated, and no validation would catch it — the id is a",
          "perfectly good integer.",
          "",
          "The fix is to make ownership part of the query rather than a check after it:",
          "",
          "```js",
          "const submission = await db.findSubmissionForGrader(req.params.id, user.id);",
          "if (!submission) return notFound();",
          "```",
          "",
          "Now there is no path that returns a row the caller is not entitled to, because the",
          "unentitled row was never fetched. A check you can forget to write is weaker than a query",
          "that cannot return the wrong thing.",
        ].join("\n"),
        diagram: {
          title: "Role check passes, object check missing",
          frames: [
            {
              label: "The request",
              caption:
                "A signed-in instructor asks for submission 91, which belongs to a different instructor's cohort. The id is a valid integer.",
              code: "GET /instructor/submissions/91   (as instructor 4)",
            },
            {
              label: "Role check: passes",
              caption:
                "The caller is an instructor, so the coarse check is satisfied. This is the check almost everyone remembers to write.",
              code: "if (user.role !== 'instructor') return forbid();   // passes",
            },
            {
              label: "Object check: absent",
              caption:
                "The row is fetched by id alone. Nothing ties it to this caller, so any id returns its row. Validation cannot detect this -- the input is well formed.",
              code: "findSubmission(91)   -> returns another cohort's row",
            },
            {
              label: "Ownership in the query",
              caption:
                "Scope the fetch by the caller. An unentitled row is never retrieved, so there is no later check to forget.",
              code: "findSubmissionForGrader(91, user.id)   -> null",
            },
          ],
        },
      },
      {
        kind: "explain",
        title: "Roles, permissions, and one table to decide",
        body: [
          "Scattered `if (role === ...)` comparisons drift. Two endpoints disagree about who may",
          "read a report, and nobody can answer \"what can an instructor do?\" without grepping.",
          "",
          "The alternative is a **table**: permissions as data, one function to consult it.",
          "",
          "```js",
          "const PERMISSIONS = {",
          "  student:    ['course:read', 'quiz:take', 'submission:create'],",
          "  instructor: ['course:read', 'submission:read', 'submission:grade'],",
          "  admin:      ['*'],",
          "};",
          "function can(role, permission) { /* consult the table */ }",
          "```",
          "",
          "Three properties this buys, and they are the reasons rather than tidiness.",
          "",
          "**It is reviewable.** The whole policy is one object a person can read in a minute.",
          "",
          "**It is testable.** You can assert the negative cases — that a student cannot grade —",
          "which is the half that scattered `if`s never get tests for.",
          "",
          "**Role hierarchy is expressed once.** \"Staff satisfy student-scoped routes\" is a",
          "property of the table, not a rule each endpoint re-implements. This application does",
          "exactly this: a frozen `ROLES_SATISFYING` map and a single `roleSatisfies` function, with",
          "a comment naming the two rules an ad-hoc comparison gets wrong — that staff satisfy",
          "student routes, and that the scheduled-job level is satisfied by *no* user role at all.",
          "",
          "Fail closed. An unknown role, an unknown permission, an unmapped route: deny. A default",
          "of \"allow\" means every gap in the table is a hole, and there will be gaps.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "A permission table with an object-level check",
        language: "javascript",
        goal:
          "Implement can() and canGrade(), then satisfy the assertions — including the ones that must be refused.",
        hint:
          "`can` handles the role question and must fail closed on an unknown role. `canGrade` must ask both questions: the permission AND whether the submission belongs to this grader's cohort.",
        starterCode: [
          "const PERMISSIONS = {",
          "  student:    ['course:read', 'quiz:take', 'submission:create'],",
          "  instructor: ['course:read', 'submission:read', 'submission:grade'],",
          "  admin:      ['*'],",
          "};",
          "",
          "// TODO: return true only when `role` holds `permission`.",
          "// Admin's '*' grants everything. An unknown role or permission denies.",
          "function can(role, permission) {",
          "}",
          "",
          "const SUBMISSIONS = {",
          "  91: { id: 91, cohortId: 1, studentId: 7 },",
          "  92: { id: 92, cohortId: 2, studentId: 8 },",
          "};",
          "",
          "// TODO: both questions. The permission, AND that the submission is in a",
          "// cohort this user is responsible for. Admins are not cohort-scoped.",
          "function canGrade(user, submissionId) {",
          "}",
          "",
          "const ada   = { id: 4, role: 'instructor', cohortIds: [1] };",
          "const bo    = { id: 5, role: 'instructor', cohortIds: [2] };",
          "const cy    = { id: 6, role: 'student',    cohortIds: [1] };",
          "const root  = { id: 1, role: 'admin',      cohortIds: [] };",
          "",
          "const checks = [",
          "  ['ada grades 91 (her cohort)',      canGrade(ada, 91),  true],",
          "  ['ada grades 92 (NOT her cohort)',  canGrade(ada, 92),  false],",
          "  ['bo grades 92 (his cohort)',       canGrade(bo, 92),   true],",
          "  ['cy (student) grades 91',          canGrade(cy, 91),   false],",
          "  ['admin grades 92',                 canGrade(root, 92), true],",
          "  ['ada grades a missing submission', canGrade(ada, 999), false],",
          "  ['unknown role is denied',          can('ghost', 'course:read'), false],",
          "  ['unknown permission is denied',    can('admin', ''), false],",
          "];",
          "",
          "for (const [label, actual, expected] of checks) {",
          "  console.log(actual === expected ? 'PASS' : 'FAIL', '-', label);",
          "}",
        ].join("\n"),
        body: [
          "Note which assertions are the interesting ones: the four that expect `false`.",
          "",
          "\"Ada grades 91\" passing tells you the happy path works. \"Ada grades 92\" failing is the",
          "vulnerability test, and it is the one an implementation that only checks the role will",
          "get wrong. Authorization tests are mostly negative tests, which is precisely why",
          "authorization written as scattered `if`s ends up untested.",
          "",
          "The missing-submission case is worth a thought too. Returning \"not found\" rather than",
          "\"forbidden\" for a row the caller may not see is deliberate: \"forbidden\" confirms the",
          "record exists, which is information a stranger should not get from a numeric guess.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Which check is missing?",
        prompt:
          "An endpoint verifies the caller is an instructor, then loads and returns the submission whose id is in the URL. What is wrong?",
        options: [
          {
            text: "There is no object-level check — any instructor can read any submission by changing the id",
            correct: true,
          },
          { text: "Nothing, provided the id is validated as a positive integer" },
          { text: "The role should be read from the request rather than the session" },
          { text: "Nothing, provided the response omits the student's password hash" },
        ],
        explanation:
          "The role check answers 'may an instructor read submissions', not 'may THIS instructor read THIS submission'. Validating the id makes it well formed, which is not the same as permitted. The scope belongs in the query — load the submission for this grader — so an unentitled row is never fetched. Reading the role from the request would be far worse, not better: a client-supplied role is a client-supplied privilege. And omitting the password hash is a genuinely necessary rule about payloads, but it does nothing about reading a record you are not entitled to.",
        body: "This shape, in production code, is worth being able to spot in a single reading.",
      },
      {
        kind: "explain",
        title: "Where the check must live",
        body: [
          "Two closing rules about placement, both of which are about removing chances to forget.",
          "",
          "**Server-side, always. Client-side, additionally.** Hiding a button is a courtesy to the",
          "user, not a control. Anything the browser can request, someone can request directly.",
          "That includes the endpoints a single-page app calls, and — a point that catches people",
          "out — **a server action is a public POST target**. It is reachable by anything that can",
          "form a request, so it needs the same guard a route handler does. This repository's own",
          "review checklist names server actions explicitly for exactly that reason.",
          "",
          "**One enforcement point, consulted everywhere.** A single guard function, called at the",
          "top of every protected operation, with the policy in one table behind it. Not because",
          "duplication is untidy, but because a second copy will disagree with the first, and the",
          "one that disagrees will be the one nobody tests.",
          "",
          "Then the operational habits: default to deny, so a new route that forgets its guard is",
          "closed rather than open; make the *absence* of a guard detectable — this application",
          "does it by requiring every route to appear in one authorization map, so a missing entry",
          "is a compile error rather than a silent hole; log authorization failures, because a burst",
          "of them is a signal; and write the negative tests, since a suite that only proves the",
          "permitted case passes proves nothing about the forbidden one.",
        ].join("\n"),
      },
    ],
  },
];
