// =============================================================================
// DBMS TRACK — beginner level, six modules.
// -----------------------------------------------------------------------------
// Slugs, titles, estimated minutes, step kinds and step subjects come from the
// `dbms` beginner ladder in docs/research/CURRICULUM_PLAN.md. Prose, fixtures,
// starter SQL and check options are written here.
//
// EVERY LAB RUNS SQLITE IN THE BROWSER via sql.js, so the dialect in the labs is
// SQLite. Where PostgreSQL behaves differently, the prose says so rather than
// letting a student generalise from SQLite's looser type handling.
//
// sqljs-worker.ts documents that SQLite has no stdin, so `setup` carries the
// schema and fixture rows and its output is discarded. That means every lab starts
// from the SAME seeded database, and a student's own statements are the only thing
// that produces visible output.
// =============================================================================

import type { SeedModule } from "./types";

/**
 * The fixture every lab in this track starts from. Small on purpose: a student has
 * to be able to verify a result by counting rows on screen, which stops being
 * possible somewhere around twenty.
 */
const FIXTURE = [
  "CREATE TABLE students (",
  "  id      INTEGER PRIMARY KEY,",
  "  name    TEXT    NOT NULL,",
  "  email   TEXT    NOT NULL UNIQUE,",
  "  city    TEXT",
  ");",
  "",
  "CREATE TABLE courses (",
  "  id     INTEGER PRIMARY KEY,",
  "  code   TEXT    NOT NULL UNIQUE,",
  "  title  TEXT    NOT NULL,",
  "  credits INTEGER NOT NULL DEFAULT 10",
  ");",
  "",
  "CREATE TABLE enrolments (",
  "  id         INTEGER PRIMARY KEY,",
  "  student_id INTEGER NOT NULL REFERENCES students(id),",
  "  course_id  INTEGER NOT NULL REFERENCES courses(id),",
  "  score      INTEGER,",
  "  UNIQUE (student_id, course_id)",
  ");",
  "",
  "INSERT INTO students (id, name, email, city) VALUES",
  "  (1, 'Ada Nwosu',      'ada@example.test',   'Lagos'),",
  "  (2, 'Bo Chen',        'bo@example.test',    'Karachi'),",
  "  (3, 'Cy Okafor',      'cy@example.test',    'Lagos'),",
  "  (4, 'Dara Iqbal',     'dara@example.test',  'Nairobi'),",
  "  (5, 'Eze Balogun',    'eze@example.test',   NULL);",
  "",
  "INSERT INTO courses (id, code, title, credits) VALUES",
  "  (1, 'WEB101', 'HTML and CSS Foundations', 10),",
  "  (2, 'JS201',  'JavaScript Fundamentals',  15),",
  "  (3, 'DB301',  'Relational Databases',     15);",
  "",
  "INSERT INTO enrolments (id, student_id, course_id, score) VALUES",
  "  (1, 1, 1, 88),",
  "  (2, 1, 2, 74),",
  "  (3, 2, 1, 55),",
  "  (4, 2, 3, 91),",
  "  (5, 3, 2, 67),",
  "  (6, 3, 3, 43),",
  "  (7, 4, 1, 72),",
  "  (8, 4, 2, NULL);",
].join("\n");

export const dbmsModules: SeedModule[] = [
  // -------------------------------------------------------------------------
  {
    slug: "dbms-what-a-database-is",
    track: "dbms",
    title: "What a Database Buys You",
    summary:
      "A database is not a file format; it is a set of guarantees about concurrent access, durability and consistency that you would otherwise have to write yourself.",
    level: "beginner",
    estimatedMinutes: 30,
    refs: [
      "https://www.w3schools.com/sql/sql_intro.asp",
      "https://www.postgresql.org/docs/current/tutorial-arch.html",
    ],
    steps: [
      {
        kind: "explain",
        title: "Files versus a database",
        body: [
          "You could store this platform's data in JSON files. Ask what you would then have to",
          "build.",
          "",
          "**Concurrency.** Two students submit at the same moment. Both read the file, both add",
          "their row, both write. One row is gone, and nothing reported an error. Fixing this",
          "properly means a locking protocol.",
          "",
          "**Durability.** The process dies halfway through the write. You now hold a truncated",
          "file. Surviving that means writing to a temporary file and renaming atomically, and",
          "knowing which platforms guarantee that rename.",
          "",
          "**Constraints.** Nothing stops two students sharing an email address, or a score of",
          "`\"seventy\"`, or an enrolment pointing at a deleted course. Each rule becomes",
          "application code that every writer has to remember to call.",
          "",
          "**Querying.** \"Average score per course, for students in Lagos, top ten\" is a",
          "loop you write, tune and debug.",
          "",
          "A DBMS is those four things, already built, already tested, and enforced no matter",
          "which application connects. That is what you are buying — not a place to put bytes.",
        ].join("\n"),
        diagram: {
          title: "Four guarantees you would otherwise write",
          frames: [
            {
              label: "Concurrency",
              caption:
                "Two writers, one file: the second write silently discards the first. A database serialises this for you, and can be asked to refuse rather than lose.",
              code: "read -> modify -> write   x2   =>   one update lost",
            },
            {
              label: "Durability",
              caption:
                "A crash mid-write leaves a truncated file. A committed transaction survives the crash; an uncommitted one leaves no trace.",
              code: "COMMIT;   -- durable from here",
            },
            {
              label: "Constraints",
              caption:
                "UNIQUE, NOT NULL, CHECK and FOREIGN KEY are enforced for every connection, including the console session nobody told you about.",
              code: "email TEXT NOT NULL UNIQUE",
            },
            {
              label: "Declarative queries",
              caption:
                "You state the result you want; the planner chooses the loops and the indexes. Rewriting the plan does not mean rewriting your code.",
              code: "SELECT course_id, AVG(score) FROM enrolments GROUP BY course_id;",
            },
          ],
        },
      },
      {
        kind: "explain",
        title: "The relational model in one page",
        body: [
          "Four words, and then you have it.",
          "",
          "A **relation** is a table: a set of rows with the same named columns. A **tuple** is",
          "one row. An **attribute** is one column, with a type. A **key** is a set of attributes",
          "that identifies a row uniquely.",
          "",
          "Two properties follow, and both matter more than they sound.",
          "",
          "**A table is a set, so row order carries no meaning.** Without `ORDER BY`, the",
          "database may return rows in any order, and the order it happens to return today is",
          "not a promise about tomorrow. Code that depends on unordered results is code with a",
          "bug that has not fired yet.",
          "",
          "**Relationships are values, not pointers.** `enrolments.student_id` holds the number",
          "`1`; it does not hold a memory address. Joining is how you follow it. That makes",
          "relationships durable across restarts, backups and machines, which is exactly what",
          "in-memory object graphs are not.",
          "",
          "`NULL` is the ragged edge of the model: it means \"no value here\", it is not equal to",
          "anything including itself, and it will surprise you at least once per project.",
          "`dbms-subqueries-and-set-operations` is where it bites hardest.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Your first SELECT",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Look at all three tables, then write one SELECT that returns only the columns you actually want.",
        hint:
          "Run one statement at a time to read its output clearly. `SELECT name, city FROM students;` returns two columns; `SELECT *` returns all of them.",
        starterCode: [
          "-- A seeded database is already loaded: students, courses, enrolments.",
          "-- Run this as-is first, then edit.",
          "",
          "SELECT * FROM students;",
          "",
          "-- TODO: return only name and city, for students in Lagos.",
          "-- TODO: return every column of courses, then narrow it to code and title.",
        ].join("\n"),
        body: [
          "The fixture is created before your statements run and its own output is discarded, so",
          "everything you see below the editor is the result of *your* queries.",
          "",
          "Notice that `SELECT *` is convenient here and a liability in application code: it",
          "returns whatever columns exist today, so adding a column changes your result shape",
          "without you touching the query.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Declarative querying",
        body: [
          "SQL is unusual: you describe the result, not the procedure.",
          "",
          "```sql",
          "SELECT s.name, AVG(e.score)",
          "FROM students s JOIN enrolments e ON e.student_id = s.id",
          "GROUP BY s.name;",
          "```",
          "",
          "Nothing there says which table to read first, whether to build a hash table or sort",
          "both sides, or whether to use an index. The **query planner** decides, using statistics",
          "about how many rows are actually in each table and how selective each predicate is.",
          "",
          "This is why the same query gets faster when you add an index, without an edit. And why",
          "a query that is instant on 100 rows can become unusable at 10 million: the planner",
          "changed its mind about the strategy, correctly, based on new statistics.",
          "",
          "The consequence for you: when SQL is slow, the question is not \"how do I write this",
          "loop better\" but \"what plan did the planner choose, and why\". `EXPLAIN` is how you",
          "ask. That is an advanced module in this track, but the habit starts here — treat the",
          "plan as the thing you are optimising, not the text.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Whose job is uniqueness?",
        prompt:
          "Two students must never share an email address. Where does that rule belong?",
        options: [
          {
            text: "A UNIQUE constraint in the database, because it holds for every connection and under concurrency",
            correct: true,
          },
          {
            text: "An application check before insert, because it can return a friendlier error",
          },
          { text: "Both, with the application check as the actual enforcement" },
          { text: "Neither; duplicate emails are a data-cleaning problem" },
        ],
        explanation:
          "A `SELECT ... WHERE email = ?` followed by an `INSERT` is two statements, and two concurrent registrations can both pass the SELECT before either INSERTs. Only the database can decide this atomically, which is what a UNIQUE index does. An application check is still worth having — for the friendly message — but it is a nicety layered on top of the guarantee, never the guarantee itself. Catch the unique-violation error and turn it into your friendly message.",
        body: "This distinction repeats throughout the track. It is the one to get right first.",
      },
      {
        kind: "explain",
        title: "Where a relational database is the wrong choice",
        body: [
          "Briefly and honestly, because the answer is not \"never\".",
          "",
          "**A cache.** If the data is derived, small and disposable, a key-value store in memory",
          "is a better fit than a table you have to keep clean.",
          "",
          "**Large binary blobs.** Video and images belong in object storage with a URL in the",
          "database. Rows containing megabytes make backups slow and every query heavier.",
          "",
          "**Genuinely schemaless, deeply variable documents.** If every record has a different",
          "shape and you never query across shapes, a document store fits the access pattern",
          "better. Note the *and*: PostgreSQL's `jsonb` covers most of the middle ground",
          "perfectly well, which is why this app uses it for a lecture's resources.",
          "",
          "**Deep graph traversal.** \"Shortest path between two people\" is a recursive join in",
          "SQL and a native operation in a graph database.",
          "",
          "**Very high write throughput of independent events.** Append-only log systems are",
          "built for that shape and relational databases are not.",
          "",
          "For most applications — including this one — a relational database with real",
          "constraints is the boring correct default, and the reason is the four guarantees you",
          "would otherwise be writing yourself.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "dbms-tables-columns-and-types",
    track: "dbms",
    title: "Tables, Columns and Types",
    summary:
      "Choosing a column's type is the cheapest constraint you will ever add, and the most expensive to change later.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/sql/sql_create_table.asp",
      "https://www.w3schools.com/sql/sql_check.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "CREATE TABLE, NOT NULL, DEFAULT",
        body: [
          "```sql",
          "CREATE TABLE enrolments (",
          "  id         INTEGER PRIMARY KEY,",
          "  student_id INTEGER NOT NULL,",
          "  course_id  INTEGER NOT NULL,",
          "  score      INTEGER,",
          "  created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP",
          ");",
          "```",
          "",
          "Read the column list as a set of promises to every future reader.",
          "",
          "`NOT NULL` says this column always has a value, so no query has to handle its absence.",
          "Leaving it off is not neutral — it tells readers that `NULL` is meaningful here, and",
          "they will write code to handle it.",
          "",
          "`score INTEGER` with no `NOT NULL` is deliberate above: an enrolment exists before it",
          "is marked, and `NULL` means \"not marked yet\". That is a real distinction from `0`,",
          "which means \"marked, scored zero\". Collapsing the two is how averages end up wrong.",
          "",
          "`DEFAULT` fills a value the writer did not supply. It applies on `INSERT`, not",
          "retroactively — adding a default to an existing table does nothing to the rows already",
          "in it.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Create a table with real constraints",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Create an `attendance` table with typed, NOT NULL columns and a sensible default, then insert one row.",
        hint:
          "A boolean in SQLite is conventionally `INTEGER NOT NULL DEFAULT 0` — SQLite has no BOOLEAN type. PostgreSQL does.",
        starterCode: [
          "-- TODO: create a table `attendance` with:",
          "--   id          integer primary key",
          "--   student_id  integer, required",
          "--   course_id   integer, required",
          "--   attended    0 or 1, required, defaulting to 0",
          "--   noted_at    text, required, defaulting to the current timestamp",
          "",
          "",
          "-- Then insert one row supplying ONLY student_id and course_id,",
          "-- and select it back to see what the defaults filled in.",
        ].join("\n"),
        body: [
          "The point of the second half is to see defaults actually applied. Supply only the two",
          "required values and read back what the database put in the other two.",
          "",
          "SQLite is unusually relaxed about types — it will accept `'hello'` in an `INTEGER`",
          "column. PostgreSQL refuses. Do not build a habit on SQLite's tolerance; write the",
          "type you mean.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Text, numeric, and the date you stored as text",
        body: [
          "Storing a date as text is the mistake that costs most later, so it is worth being",
          "concrete about why.",
          "",
          "`'2026-07-30'` sorts correctly by luck: ISO-8601 happens to sort lexicographically.",
          "`'30/07/2026'` does not, and `'March 3'` is not going anywhere near an `ORDER BY`.",
          "",
          "More importantly, text does not do date arithmetic. \"Enrolments in the last 30 days\"",
          "and \"days between submission and deadline\" need a date type. In text you get string",
          "comparison, and every calculation moves into the application, differently in each one",
          "that touches the column.",
          "",
          "And text does not validate. `'2026-02-31'` is a perfectly good string and not a day",
          "that exists. A `DATE` column rejects it; a `TEXT` column stores it and you find out",
          "when a report divides by it.",
          "",
          "Same argument for numbers. A score stored as text will not average, and `'9' > '10'`",
          "is true in string comparison. Money deserves its own note: use a decimal type or",
          "integer minor units (`cents`), never a float, because `0.1 + 0.2` is not `0.3` in",
          "binary floating point and a ledger that is off by a cent is off.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "A score that is always 0 to 100",
        prompt: "How do you model a score that must be between 0 and 100 inclusive?",
        options: [
          {
            text: "An integer column with a CHECK constraint restricting it to 0..100",
            correct: true,
          },
          { text: "A text column, validated in the application before every insert" },
          { text: "An integer column, relying on the application to stay in range" },
          { text: "A float column, so partial marks are possible later" },
        ],
        explanation:
          "The type stops `'ninety'`; the CHECK stops `150` and `-5`. Both are enforced for every connection, including a console session and a future script nobody has written yet. Application validation is worth having for the error message, but as the only defence it lasts exactly until the second writer. Choosing float 'in case of partial marks' is a real design decision to make deliberately, not a hedge — and if you do, CHECK the range anyway.",
        body: "Two constraints, not one. Name both.",
      },
      {
        kind: "lab",
        title: "Watch a CHECK refuse a row",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Add a CHECK-constrained table, insert a valid row, then insert an out-of-range one and read the error.",
        hint:
          "`CHECK (score BETWEEN 0 AND 100)` goes in the column or table definition. The failing INSERT will report a constraint violation and insert nothing.",
        starterCode: [
          "CREATE TABLE marks (",
          "  id         INTEGER PRIMARY KEY,",
          "  student_id INTEGER NOT NULL,",
          "  score      INTEGER NOT NULL",
          "  -- TODO: add a CHECK restricting score to 0..100",
          ");",
          "",
          "INSERT INTO marks (student_id, score) VALUES (1, 88);",
          "",
          "-- TODO: now insert score = 150 and read what comes back.",
          "",
          "SELECT * FROM marks;",
        ].join("\n"),
        body: [
          "The final `SELECT` is the important line. It shows the failed insert left *nothing*",
          "behind — the constraint refused the row rather than storing a clamped version of it.",
          "",
          "That is the behaviour you want: a rejected write is visible immediately at the point",
          "of the mistake. Silently clamping to 100 would have produced a plausible, wrong number",
          "and no error at all.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "ALTER TABLE, and why migrations exist",
        body: [
          "`ALTER TABLE` changes a live schema, and a live schema has code running against it.",
          "That is the whole difficulty.",
          "",
          "Adding a nullable column is safe: old code ignores it, new code uses it. Adding a",
          "`NOT NULL` column with no default is not — existing rows have no value to put there,",
          "so the statement fails, or (worse, historically) rewrites the whole table while",
          "holding a lock that blocks every reader.",
          "",
          "Renaming or dropping a column breaks any deployed code still referring to it, and",
          "during a rolling deploy both versions are live at once.",
          "",
          "Which is why schema changes are **migrations**: ordered, versioned files, applied once,",
          "recorded, and reviewed like code. This repository has them under",
          "`src/db/migrations/`, and its own rule is that the schema is frozen between",
          "coordinated changes precisely because parallel work against a moving schema does not",
          "converge.",
          "",
          "The pattern for a breaking change is *expand and contract*: add the new nullable",
          "column, backfill it, switch the code, then enforce and drop the old one — four",
          "deploys, each individually safe. The advanced module in this track walks it through.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "dbms-select-filter-sort",
    track: "dbms",
    title: "Selecting, Filtering and Sorting",
    summary:
      "Most real queries are a projection, a filter and an order, and getting those three right accounts for most of day-to-day SQL.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/sql/sql_where.asp",
      "https://www.w3schools.com/sql/sql_orderby.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "Projection, filter, order, limit",
        body: [
          "Four clauses, and they are applied in a different order from the one you write them",
          "in:",
          "",
          "```sql",
          "SELECT name, score        -- 3. projection: which columns come back",
          "FROM enrolments e         -- 1. source",
          "WHERE score >= 70         -- 2. filter: which rows survive",
          "ORDER BY score DESC       -- 4. order",
          "LIMIT 10;                 -- 5. cut",
          "```",
          "",
          "Knowing that `WHERE` runs before `SELECT` explains a common error: you cannot filter",
          "on a column alias defined in the `SELECT` list, because it does not exist yet.",
          "",
          "Two habits worth forming now.",
          "",
          "**Drop `SELECT *` in application code.** It returns whatever columns exist today, so",
          "adding one changes your result shape silently, and it drags text and blob columns",
          "across the network that nobody asked for.",
          "",
          "**`LIMIT` without `ORDER BY` is not a top-ten, it is ten arbitrary rows.** A table is",
          "a set; there is no default order to take the first of. It will look right in testing",
          "and change when the planner does.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Top ten by score",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Return student name and score for the highest-scoring enrolments, newest first, with only the two columns you need.",
        hint:
          "You need a join to get the name: `FROM enrolments e JOIN students s ON s.id = e.student_id`. Then ORDER BY score DESC.",
        starterCode: [
          "-- TODO: student name and score only, highest score first, at most 10 rows.",
          "-- No SELECT *.",
          "",
          "",
          "-- Then run the same query WITHOUT the ORDER BY and compare.",
          "-- Which one is a 'top ten'?",
        ].join("\n"),
        body: [
          "Note what happens to the unscored enrolment (student 4, course 2, `score` is `NULL`).",
          "",
          "SQLite sorts `NULL` first ascending and last descending; PostgreSQL's default is the",
          "opposite for descending unless you say `NULLS LAST`. If where the unknowns land",
          "matters to your result — and in a leaderboard it does — say so explicitly rather than",
          "inheriting whichever engine you happen to be on.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "AND, OR, and the parentheses that save you",
        body: [
          "`AND` binds tighter than `OR`. Always. So this:",
          "",
          "```sql",
          "WHERE score > 50 OR passed = 1 AND active = 1",
          "```",
          "",
          "is read by the database as:",
          "",
          "```sql",
          "WHERE score > 50 OR (passed = 1 AND active = 1)",
          "```",
          "",
          "Almost nobody means that. The intended reading is usually",
          "`(score > 50 OR passed = 1) AND active = 1`, and the two differ on exactly the rows",
          "that matter: an inactive student scoring 80 is *included* by the first and excluded by",
          "the second.",
          "",
          "It is the sort of bug that produces a plausible number rather than an error, so it",
          "survives review and lands in a report.",
          "",
          "The habit is not \"remember the precedence\". It is: **parenthesise any mixed AND/OR",
          "condition, every time**, even when the precedence already agrees with you. It costs two",
          "characters and removes the class.",
          "",
          "`NOT` binds tighter still, and `NOT a = b` is not `a != b` when `NULL` is involved —",
          "which is the subject of a later module.",
        ].join("\n"),
        diagram: {
          title: "Where the brackets go",
          frames: [
            {
              label: "What you wrote",
              caption:
                "No brackets. Reads naturally left to right, which is not how the database reads it.",
              code: "WHERE score > 50 OR passed = 1 AND active = 1",
            },
            {
              label: "What the database read",
              caption:
                "AND binds tighter, so the AND pair is grouped first. An inactive student scoring 80 satisfies the first branch and is included.",
              code: "WHERE score > 50 OR (passed = 1 AND active = 1)",
            },
            {
              label: "What you meant",
              caption:
                "Either condition, but only for active students. The inactive high scorer is now excluded.",
              code: "WHERE (score > 50 OR passed = 1) AND active = 1",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "IN, BETWEEN and LIKE",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Filter three ways against the seeded data, then combine two of them and bracket the condition explicitly.",
        hint:
          "`IN ('Lagos','Nairobi')`, `BETWEEN 60 AND 80` (inclusive at both ends), `LIKE '%example.test'` where `%` matches any run of characters.",
        starterCode: [
          "-- 1. Students in Lagos or Nairobi, using IN.",
          "",
          "-- 2. Enrolments scoring between 60 and 80 inclusive, using BETWEEN.",
          "",
          "-- 3. Students whose email ends in 'example.test', using LIKE.",
          "",
          "-- 4. Now combine 1 and 2 in one query over a join, and bracket the",
          "--    condition explicitly even if you think you do not need to.",
        ].join("\n"),
        body: [
          "Three things to notice.",
          "",
          "`BETWEEN` is inclusive at both ends — `BETWEEN 60 AND 80` includes 60 and 80. For",
          "dates that catches people out: `BETWEEN '2026-01-01' AND '2026-01-31'` silently",
          "excludes almost all of the 31st once times are involved. Prefer `>= start AND < next`.",
          "",
          "`LIKE '%text'` with a leading wildcard cannot use an ordinary index — the index is",
          "sorted by prefix, and you have not given it one.",
          "",
          "`IN` on a list of literals is fine. `IN` on a subquery has a `NULL` trap that has its",
          "own module.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Why does that WHERE surprise people?",
        prompt:
          "`WHERE score > 50 OR passed = 1 AND active = 1` — which rows does the database actually return?",
        options: [
          {
            text: "Any row scoring over 50 regardless of active, plus rows that are both passed and active",
            correct: true,
          },
          { text: "Only active rows that either score over 50 or are passed" },
          { text: "Only rows satisfying all three conditions" },
          { text: "The clauses are evaluated left to right, so it matches (score > 50 OR passed = 1) first" },
        ],
        explanation:
          "`AND` has higher precedence than `OR`, so the condition groups as `score > 50 OR (passed = 1 AND active = 1)`. The `active = 1` requirement therefore applies only to the second branch — an inactive row scoring 60 comes back. The fix is brackets, and the habit is to write them on every mixed condition rather than to memorise the table.",
        body: "Predict the answer before choosing. This one is worth getting wrong once, cheaply, here.",
      },
      {
        kind: "explain",
        title: "DISTINCT, and what it costs",
        body: [
          "`SELECT DISTINCT city FROM students` removes duplicate rows from the result. To do",
          "that the database must compare every row with every other one, which in practice means",
          "sorting or hashing the whole result set before returning anything.",
          "",
          "On a small result that is free. On a large one it is the most expensive part of the",
          "query, and it defeats streaming: nothing can be sent until everything has been seen.",
          "",
          "But the cost is not the main point. **`DISTINCT` is very often a symptom.** When a",
          "join produces duplicates, that usually means the join multiplied rows — a student with",
          "three enrolments appearing three times — and `DISTINCT` hides the multiplication",
          "rather than fixing it. The result looks right and the next aggregate over the same",
          "join is wrong.",
          "",
          "So when you reach for `DISTINCT`, first ask where the duplicates came from. Often the",
          "honest fix is `EXISTS` instead of a join (you wanted \"has at least one\", not \"one row",
          "per\"), or a `GROUP BY` that states the grain you actually want.",
          "",
          "`DISTINCT` on a genuinely distinct list of values — the set of cities — is exactly the",
          "right tool and nothing to apologise for.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "dbms-aggregates-and-grouping",
    track: "dbms",
    title: "Aggregates and Grouping",
    summary:
      "GROUP BY is where SQL stops looking like row-by-row code, and where the WHERE/HAVING distinction first bites.",
    level: "beginner",
    estimatedMinutes: 40,
    refs: [
      "https://www.w3schools.com/sql/sql_groupby.asp",
      "https://www.w3schools.com/sql/sql_having.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "COUNT, SUM, AVG, MIN, MAX",
        body: [
          "An aggregate collapses many rows into one value.",
          "",
          "```sql",
          "SELECT COUNT(*), AVG(score), MIN(score), MAX(score) FROM enrolments;",
          "```",
          "",
          "One row out, whatever the input size. The detail is gone, which is the point.",
          "",
          "The thing to internalise now, because it causes more wrong numbers than anything else",
          "in this module: **aggregates other than `COUNT(*)` skip `NULL`**.",
          "",
          "Our fixture has eight enrolments and one of them is unmarked. So `COUNT(*)` is 8,",
          "`COUNT(score)` is 7, and `AVG(score)` divides by 7, not 8. That is almost certainly",
          "what you want — an unmarked enrolment should not drag the average toward zero — but it",
          "means `SUM(score) / COUNT(*)` and `AVG(score)` are different numbers, and only one of",
          "them is the average score.",
          "",
          "`COUNT(*)` counts rows. `COUNT(col)` counts non-null values of that column. They are",
          "different questions, and choosing between them is choosing what you are asking.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Average score per course",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Compute the average score per course with the course title, and show how many enrolments each average is based on.",
        hint:
          "Every non-aggregated column in the SELECT list must appear in the GROUP BY. Include both `COUNT(*)` and `COUNT(score)` to see the gap.",
        starterCode: [
          "-- TODO: per course, return title, average score, COUNT(*) and COUNT(score).",
          "-- Group by whatever your non-aggregated columns are.",
          "",
          "",
          "-- Look at JS201. Why do its two counts differ, and which one",
          "-- is the average's denominator?",
        ].join("\n"),
        body: [
          "Reporting the count next to the average is a habit worth keeping. \"Average 91\" from",
          "one enrolment and \"average 91\" from four hundred are different facts, and the number",
          "alone cannot tell them apart.",
          "",
          "PostgreSQL will refuse a non-aggregated column missing from the `GROUP BY`. SQLite",
          "allows it and picks an arbitrary row's value — convenient, and a silent source of",
          "wrong reports. Write the `GROUP BY` PostgreSQL would demand.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "WHERE filters rows; HAVING filters groups",
        body: [
          "The order of operations makes this obvious once you have it:",
          "",
          "```",
          "FROM      -> the rows",
          "WHERE     -> throw rows away          (before grouping)",
          "GROUP BY  -> collapse into groups",
          "HAVING    -> throw groups away        (after grouping)",
          "SELECT    -> project",
          "ORDER BY  -> sort",
          "```",
          "",
          "`WHERE` runs before groups exist, so it cannot mention an aggregate — there is nothing",
          "to aggregate over yet. `HAVING` runs after, so it can, and that is what it is for.",
          "",
          "```sql",
          "SELECT course_id, AVG(score) AS avg_score",
          "FROM enrolments",
          "WHERE score IS NOT NULL      -- drop unmarked rows first",
          "GROUP BY course_id",
          "HAVING AVG(score) > 60;      -- then drop weak courses",
          "```",
          "",
          "The two are not interchangeable, and the difference is not just syntax: filtering rows",
          "changes what the aggregate is computed *from*, while filtering groups only changes",
          "which computed results you keep. `WHERE score > 50` then `AVG(score)` gives you \"the",
          "average of the passing scores\". `HAVING AVG(score) > 50` gives you \"courses whose",
          "overall average passed\". Different questions, different answers.",
          "",
          "Prefer `WHERE` when either would work — it discards rows earlier, so there is less to",
          "group.",
        ].join("\n"),
        diagram: {
          title: "Two filters, two stages",
          frames: [
            {
              label: "All rows",
              caption:
                "Eight enrolments across three courses, one of them unmarked. Nothing has been discarded yet.",
              code: "FROM enrolments   -- 8 rows",
            },
            {
              label: "WHERE: drop rows",
              caption:
                "Runs before grouping, so it cannot see an average. Dropping the unmarked row here changes what every later average is computed from.",
              code: "WHERE score IS NOT NULL   -- 7 rows",
            },
            {
              label: "GROUP BY: collapse",
              caption:
                "Seven rows become three groups. From here on, the unit of work is a group, not a row.",
              code: "GROUP BY course_id   -- 3 groups",
            },
            {
              label: "HAVING: drop groups",
              caption:
                "Runs after the averages exist, so it can test one. It removes whole courses; it does not change any average.",
              code: "HAVING AVG(score) > 60   -- 2 groups",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "HAVING in practice",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Keep only the courses whose average score exceeds 60, then move the same condition into WHERE and explain the different result.",
        hint:
          "`HAVING AVG(score) > 60` after the GROUP BY. Then try `WHERE score > 60` instead and compare both the row sets and the averages.",
        starterCode: [
          "-- 1. Courses whose AVERAGE score is above 60.",
          "",
          "",
          "-- 2. Now write it with WHERE score > 60 and no HAVING.",
          "--    Compare the averages. They are different numbers.",
          "--    Write down, in words, what each query is actually asking.",
        ].join("\n"),
        body: [
          "The second query answers \"among scores above 60, what is the average per course\" —",
          "which is arithmetically guaranteed to be above 60 and therefore tells you nothing",
          "about whether the course is doing well.",
          "",
          "That is the trap in one line: a filter that looks like a rewrite of the same condition",
          "silently changed the question. Being able to say out loud which question a query asks",
          "is the skill this step is training.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Move COUNT(*) > 3 from HAVING to WHERE",
        prompt:
          "You move `COUNT(*) > 3` out of a HAVING clause and into WHERE. What happens?",
        options: [
          {
            text: "The query is rejected — WHERE runs before grouping, so there is no group to count",
            correct: true,
          },
          { text: "It works and is faster, because rows are filtered earlier" },
          { text: "It works but silently counts all rows in the table instead of the group" },
          { text: "It works in SQLite and fails in PostgreSQL" },
        ],
        explanation:
          "`WHERE` is evaluated per row, before `GROUP BY` has formed any group, so an aggregate there has nothing to aggregate. Every mainstream engine rejects it. The rule of thumb: a condition mentioning an aggregate belongs in `HAVING`; a condition about a single row's column values belongs in `WHERE`, where it discards rows before grouping and so does less work.",
        body: "A syntax error with a good reason behind it. State the reason.",
      },
      {
        kind: "explain",
        title: "COUNT(col) versus COUNT(*), and other NULL arithmetic",
        body: [
          "Collected in one place, because each of these has produced a wrong report somewhere.",
          "",
          "**`COUNT(*)` counts rows. `COUNT(col)` counts non-null values.** Our fixture: 8 and 7.",
          "",
          "**`AVG` divides by the non-null count.** So `AVG(score)` and `SUM(score)/COUNT(*)`",
          "differ whenever a `NULL` exists, and only the first is the average score.",
          "",
          "**`SUM` of no rows is `NULL`, not `0`.** A group that filtered down to nothing gives",
          "you `NULL`, and `NULL + 10` is `NULL`, so one empty group can propagate into a whole",
          "total. `COALESCE(SUM(score), 0)` is the fix, and it is why you see `COALESCE` around",
          "almost every `SUM` in production reporting code.",
          "",
          "**`COUNT` of no rows is `0`.** Inconsistent with `SUM`, and the inconsistency is worth",
          "memorising rather than deriving.",
          "",
          "**`NULL = NULL` is not true.** It is `NULL`, which is not true, which is why `IS NULL`",
          "exists as separate syntax. It also means `GROUP BY city` puts all the `NULL` cities in",
          "one group even though they are not equal to each other — grouping uses a different",
          "notion of sameness from `=`, and that is deliberate.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "dbms-insert-update-delete",
    track: "dbms",
    title: "Writing Data Safely",
    summary:
      "Every write statement is one missing WHERE away from touching the whole table, so the habits around writes matter more than the syntax.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/sql/sql_update.asp",
      "https://www.w3schools.com/sql/sql_delete.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "The affected-row count is your receipt",
        body: [
          "```sql",
          "INSERT INTO students (name, email) VALUES ('Fola', 'fola@example.test');",
          "UPDATE enrolments SET score = 90 WHERE id = 3;",
          "DELETE FROM enrolments WHERE id = 8;",
          "```",
          "",
          "Every one of these returns a number: how many rows it touched. Read it.",
          "",
          "An `UPDATE ... WHERE id = 3` that reports 0 rows did not fail — it succeeded at",
          "changing nothing, because no row matched. If your code treats \"no error\" as \"it",
          "worked\", that update is silently lost and the student's mark is still the old one.",
          "",
          "An `UPDATE` that reports 4 000 rows when you expected 1 has already happened. There is",
          "no undo outside a transaction.",
          "",
          "So the discipline is: expect a specific count, compare against it, and treat a",
          "mismatch as an error. In application code that is",
          "`if (result.rowCount !== 1) throw ...`. It is two lines, and it turns an entire class",
          "of silent data bug into a loud one.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Insert, then update by key",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Insert three students, update exactly one by primary key, and prove with a SELECT that only that one changed.",
        hint:
          "One `INSERT` can carry several `VALUES` tuples. Then `UPDATE students SET city = ... WHERE id = ...` and select all five rows back.",
        starterCode: [
          "-- 1. Insert three new students in one statement.",
          "",
          "-- 2. Update the city of exactly ONE of them, by id.",
          "",
          "-- 3. SELECT every student and confirm the other two are untouched.",
          "",
          "-- 4. Now run an UPDATE with a WHERE that matches nothing.",
          "--    Note that it is not an error.",
        ].join("\n"),
        body: [
          "Step 4 is the one to sit with. A write that matched nothing looks identical to a write",
          "that succeeded, from the outside. The only difference is the row count, which is why",
          "the previous step insisted you read it.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Run the SELECT first. Always.",
        body: [
          "`UPDATE enrolments SET score = 0` is valid SQL. It sets every score in the table to",
          "zero. There is no confirmation prompt, and outside a transaction there is no undo —",
          "only a restore from backup, and a conversation about how much data the backup is",
          "behind.",
          "",
          "The habit that prevents it, and it is a habit rather than a technique:",
          "",
          "1. **Write the `SELECT` first.** Same `FROM`, same `WHERE`. Look at the rows.",
          "2. **Check the count is what you expect.** Not \"looks plausible\" — the number you",
          "   predicted before you ran it.",
          "3. **Then change `SELECT ...` to `UPDATE ... SET ...`, keeping the `WHERE` untouched.**",
          "",
          "Two more guards worth having:",
          "",
          "**Wrap it.** `BEGIN;` before, `SELECT` to verify, then `COMMIT;` or `ROLLBACK;`. This",
          "gives you the undo the bare statement does not have. It is the single highest-value",
          "habit in this module.",
          "",
          "**Type the `WHERE` before the `SET`.** A half-typed `UPDATE t SET x = 1` that gets",
          "executed by an accidental keystroke hits every row; a half-typed `UPDATE t WHERE` is a",
          "syntax error. Order of typing is not superstition here.",
        ].join("\n"),
        diagram: {
          title: "The preview-then-write loop",
          frames: [
            {
              label: "Write the SELECT",
              caption:
                "Same FROM, same WHERE as the delete you intend. Nothing is modified, so a mistake here costs nothing.",
              code: "SELECT * FROM enrolments WHERE score IS NULL;",
            },
            {
              label: "Check the count",
              caption:
                "You predicted one row. If the preview shows eight, the WHERE is wrong and you have found out for free.",
              code: "-- 1 row. Expected 1. Proceed.",
            },
            {
              label: "Wrap it",
              caption:
                "BEGIN gives you an undo the bare statement does not have. This is the step people skip and regret.",
              code: "BEGIN;",
            },
            {
              label: "Swap the verb, keep the WHERE",
              caption:
                "Only the first clause changes. Then verify again and COMMIT -- or ROLLBACK if the count surprised you.",
              code: "DELETE FROM enrolments WHERE score IS NULL;\n-- verify, then COMMIT;",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Preview, then delete",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Write the SELECT that previews a delete, confirm the row count, then run the delete with the identical WHERE.",
        hint:
          "Target the unmarked enrolment: `WHERE score IS NULL`. Preview with SELECT, count the rows, then swap the verb.",
        starterCode: [
          "-- 1. Preview: which enrolments have no score yet?",
          "SELECT * FROM enrolments WHERE score IS NULL;",
          "",
          "-- 2. How many rows was that? Write the number in a comment.",
          "",
          "-- 3. Now delete exactly those rows, reusing the SAME WHERE clause.",
          "",
          "-- 4. Confirm with a SELECT COUNT(*) that the table is now the size you expect.",
          "",
          "-- 5. For contrast, count the table, then think about what",
          "--    DELETE FROM enrolments; would have done. Do not run it.",
        ].join("\n"),
        body: [
          "The database in this lab is in memory and thrown away when the worker stops, so",
          "nothing here can be lost. That is exactly why it is the right place to build the",
          "habit — you want it automatic before you are ever connected to something real.",
          "",
          "Note that `WHERE score IS NULL` is the only way to match a null. `WHERE score = NULL`",
          "matches nothing at all, and reports success while deleting zero rows.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "How many rows does that touch?",
        prompt: "`UPDATE enrolments SET score = 0;` — what does this statement do?",
        options: [
          {
            text: "Sets every score in the table to 0, with no error and no undo outside a transaction",
            correct: true,
          },
          { text: "Nothing — an UPDATE without a WHERE is a syntax error" },
          { text: "Updates only the first row, since no row was identified" },
          { text: "Prompts for confirmation before applying" },
        ],
        explanation:
          "An `UPDATE` with no `WHERE` matches every row, by definition rather than by accident — the clause is optional and its absence means 'all'. Some interactive clients offer a safety setting that refuses unqualified writes, and it is worth switching on, but it is a client feature and not a property of SQL. The durable protections are the preview `SELECT` and wrapping the statement in a transaction.",
        body: "The answer is unglamorous. Being certain of it is the point.",
      },
      {
        kind: "explain",
        title: "Upsert, and why check-then-insert races",
        body: [
          "\"Insert it if it is not there, otherwise update it\" is one of the most common things",
          "an application needs, and the obvious implementation is wrong:",
          "",
          "```sql",
          "SELECT id FROM progress WHERE student_id = 1 AND step_id = 7;   -- none",
          "INSERT INTO progress (student_id, step_id) VALUES (1, 7);",
          "```",
          "",
          "Two requests can both run the `SELECT`, both see nothing, and both `INSERT`. A",
          "double-clicked button is exactly that. You get a duplicate row, or — if a unique index",
          "is protecting you — an error on the second one, which is at least loud.",
          "",
          "The atomic form pushes the decision into the database:",
          "",
          "```sql",
          "INSERT INTO progress (student_id, step_id) VALUES (1, 7)",
          "ON CONFLICT (student_id, step_id) DO NOTHING;",
          "```",
          "",
          "One statement, no window between the check and the write. `DO UPDATE SET ...` if you",
          "want the update instead of nothing.",
          "",
          "Note the prerequisite: **`ON CONFLICT` needs a unique constraint to conflict with.**",
          "The index is what makes the upsert possible, not merely a safety net beside it. This",
          "platform's own step-completion table is built exactly this way — a unique index on",
          "`(student_id, step_id)` and `ON CONFLICT DO NOTHING`, so finishing a step twice is a",
          "no-op rather than a second row.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "dbms-keys-and-uniqueness",
    track: "dbms",
    title: "Primary Keys and Uniqueness",
    summary:
      "A primary key is the answer to \"which row do you mean\", and a unique constraint is the only reliable way to stop duplicates under concurrency.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/sql/sql_primarykey.asp",
      "https://www.w3schools.com/sql/sql_unique.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "Primary, candidate, surrogate, natural",
        body: [
          "A **candidate key** is any set of columns that identifies a row uniquely. A table can",
          "have several: in `students`, both `id` and `email` qualify.",
          "",
          "The **primary key** is the candidate you nominate as *the* identifier — the one foreign",
          "keys point at and the one you quote in a bug report.",
          "",
          "A **natural key** comes from the data itself: an email, an ISBN, a course code. A",
          "**surrogate key** is a meaningless number the database invents.",
          "",
          "The trade-off is short. A natural key is readable and needs no extra column; it is",
          "also *outside your control*. Email addresses change. Course codes get reorganised.",
          "Countries change ISO codes. When a natural primary key changes, every foreign key",
          "referencing it has to change too, in one transaction, forever.",
          "",
          "A surrogate key is meaningless, which is precisely its value: nothing about the real",
          "world can make it wrong, so it never needs to change.",
          "",
          "The usual answer is both: a surrogate primary key for references, plus a `UNIQUE`",
          "constraint on the natural key so the real-world rule is still enforced. That is",
          "exactly what our `students` table does — `id` as the key, `email` as a unique column.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Watch a duplicate insert fail",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Insert a student whose email already exists, read the error, and confirm nothing was written.",
        hint:
          "`students.email` is already declared UNIQUE in the fixture. Insert 'ada@example.test' again and count the rows afterwards.",
        starterCode: [
          "SELECT COUNT(*) AS before FROM students;",
          "",
          "-- TODO: insert a NEW student using an email that already exists",
          "--       ('ada@example.test'). Read the error carefully.",
          "",
          "SELECT COUNT(*) AS after FROM students;",
          "",
          "-- TODO: now insert a student with a genuinely new email and confirm",
          "--       the count goes up by exactly one.",
        ].join("\n"),
        body: [
          "The two counts being equal is the whole lesson: the constraint refused the row rather",
          "than storing a second Ada.",
          "",
          "In application code, this error is not a failure to handle defensively — it is the",
          "*signal*. Catch the unique-violation and turn it into \"that email is already",
          "registered\". You get correctness from the database and a good message from your code,",
          "which is the right division of labour.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Auto-increment and its trade-offs",
        body: [
          "`INTEGER PRIMARY KEY AUTOINCREMENT` in SQLite, `SERIAL` or `GENERATED AS IDENTITY` in",
          "PostgreSQL: the database hands out the next number so you do not have to.",
          "",
          "What you get: uniqueness with no coordination, compact keys, and index-friendly",
          "insertion order because new rows land at the end of the B-tree rather than in the",
          "middle.",
          "",
          "What it costs:",
          "",
          "**Sequences are not transactional.** A rolled-back transaction still consumed its",
          "number, so gaps are normal. Treat the sequence as an ID generator, never as a count",
          "of anything.",
          "",
          "**They are guessable.** `/invoices/1247` invites `/invoices/1248`, and if the",
          "authorization check is missing, sequential IDs are the map to everyone else's data.",
          "The fix is the authorization check — but a UUID in a public URL removes the",
          "enumeration as well, which is why external-facing identifiers are often UUIDs even",
          "when the internal key is an integer.",
          "",
          "**They leak volume.** Two orders placed a week apart with IDs 5 and 9 tell a",
          "competitor how many orders you take.",
          "",
          "**They need the database to assign them.** A client that must know an ID before",
          "inserting — offline-first apps, distributed writers — needs a UUID generated at the",
          "edge instead.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Why is an application check not a substitute?",
        prompt:
          "Your code runs `SELECT 1 FROM students WHERE email = ?` and only inserts when it finds nothing. Why is a UNIQUE index still required?",
        options: [
          {
            text: "Two concurrent registrations can both pass the SELECT before either INSERT — only the index decides atomically",
            correct: true,
          },
          { text: "Because the SELECT might be slow without an index on email" },
          { text: "Because the application check cannot see rows inserted by other applications" },
          { text: "It is not required; the check is sufficient if it runs inside a transaction" },
        ],
        explanation:
          "The gap between the SELECT and the INSERT is the whole problem: both requests read 'not present', both write, and you have two Adas. Wrapping it in a transaction does not close the gap either — at the usual isolation level neither transaction sees the other's uninserted row, so both still proceed. Only a unique index makes the decision atomically. The second answer is a real performance point and a real reason to index the column, but it is not the correctness reason.",
        body:
          "This is the same shape as the upsert race in the previous module, and as this platform's own one-attempt exam rule. Worth recognising on sight.",
      },
      {
        kind: "lab",
        title: "A composite key",
        language: "sql",
        setup: FIXTURE,
        goal:
          "Confirm the composite unique constraint on (student_id, course_id) refuses a double enrolment but allows the same student on a different course.",
        hint:
          "The fixture declares `UNIQUE (student_id, course_id)` on enrolments. Student 1 is already on course 1 but not on course 3.",
        starterCode: [
          "-- 1. Try to enrol student 1 on course 1 again. Read the error.",
          "",
          "-- 2. Now enrol student 1 on course 3. This must succeed:",
          "--    the constraint is on the PAIR, not on either column alone.",
          "",
          "-- 3. Confirm with a SELECT.",
          "",
          "-- 4. Think about the column order in UNIQUE (student_id, course_id).",
          "--    It does not change what is rejected. Does it change anything?",
        ].join("\n"),
        body: [
          "Answer to step 4: not for uniqueness, but yes for lookups. A composite index is usable",
          "for a query on its **leftmost prefix**, so `UNIQUE (student_id, course_id)` helps",
          "\"which courses is this student on\" and does nothing for \"who is on this course\".",
          "Reverse the order and you reverse which query is fast.",
          "",
          "That is why the same constraint can be the right and the wrong way round depending on",
          "how the table is read — the advanced indexing module goes into it properly.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Keys you will regret",
        body: [
          "Concretely, the ones that keep going wrong:",
          "",
          "**Email as a primary key.** People change email addresses. Now the key changes, and",
          "every table referencing it changes with it. Unique constraint: yes. Primary key: no.",
          "",
          "**A person's name, in any combination.** Names are not unique, do change, and are not",
          "even stably spelled across systems that transliterate.",
          "",
          "**A phone number.** Reassigned by carriers. Two people, one key, months apart.",
          "",
          "**An externally administered code.** Course codes, department codes, product SKUs —",
          "all owned by someone who will reorganise them without telling you.",
          "",
          "**A composite of \"enough\" columns to be unique today.** `(name, date_of_birth, city)`",
          "is unique until the day it is not, and then the fix is a schema migration under",
          "pressure.",
          "",
          "The underlying test is one question: **who is allowed to change this value?** If the",
          "answer is anyone other than your database, it is not a primary key. Make it a `UNIQUE`",
          "column — so the real-world rule is still enforced — and let a surrogate integer be the",
          "thing foreign keys point at.",
        ].join("\n"),
      },
    ],
  },
];
