// =============================================================================
// OOP TRACK — beginner level, six modules.
// -----------------------------------------------------------------------------
// Slugs, titles, estimated minutes, step kinds and step subjects are taken from
// the `oop` beginner ladder in docs/research/CURRICULUM_PLAN.md. The PROSE, the
// starter code, the diagram frames and the check options are written here.
//
// Labs are JavaScript and Python because both have an in-browser runner and
// between them cover the prototype-based and class-based flavours of the same
// ideas. Every lab prints to stdout, because that is the only channel the
// Web Worker and Pyodide runners share.
// =============================================================================

import type { SeedModule } from "./types";

export const oopModules: SeedModule[] = [
  // -------------------------------------------------------------------------
  {
    slug: "oop-objects-and-state",
    track: "oop",
    title: "Objects and State",
    summary:
      "An object bundles data with the operations that read and change that data, so a program becomes a set of collaborating parts instead of one long script.",
    level: "beginner",
    estimatedMinutes: 30,
    refs: [
      "https://www.w3schools.com/js/js_objects.asp",
      "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_objects",
    ],
    steps: [
      {
        kind: "explain",
        title: "State, behaviour and identity",
        body: [
          "Three words describe everything an object is.",
          "",
          "**State** is the data it currently holds — a balance of 250, an owner named Ada.",
          "**Behaviour** is what it can be asked to do — deposit, withdraw, report itself.",
          "**Identity** is the fact that it is *this* object and not another one that happens",
          "to look the same.",
          "",
          "The alternative is to keep the same information in parallel collections: one array",
          "of names, one array of balances, and an unwritten rule that index 3 in each refers",
          "to the same customer. That rule is not enforced anywhere. Sort one array and the",
          "other silently describes different people. Delete from one and every later index",
          "is off by one. The bug does not appear where you made the mistake, and nothing in",
          "the code says the two arrays are related.",
          "",
          "Grouping the balance with the operations allowed on it removes the possibility.",
          "There is no index to keep in step, because there is only one thing.",
        ].join("\n"),
        diagram: {
          title: "Parallel arrays versus one object",
          frames: [
            {
              label: "Two arrays, one unwritten rule",
              caption:
                "names[2] and balances[2] describe the same customer only because everyone remembers to keep them aligned. Nothing enforces it.",
              code: 'names = ["Ada", "Bo", "Cy"]\nbalances = [10, 20, 30]',
            },
            {
              label: "The rule breaks",
              caption:
                "Sorting names alone leaves balances describing different people. No error is raised, and the wrong number is now attached to the wrong customer.",
              code: 'names.sort()  // ["Ada", "Bo", "Cy"] -> order changed\n// balances untouched',
            },
            {
              label: "One object per customer",
              caption:
                "State is grouped with the operations allowed on it. There is no second array to fall out of step, so the whole class of bug is gone.",
              code: "customer = { name: 'Ada', balance: 10, deposit(n) { ... } }",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Build an account object",
        language: "javascript",
        goal:
          "Give the account a deposit and a withdraw function, then watch both calls change the same shared balance.",
        hint:
          "Inside a method defined with `deposit(amount) { ... }`, `this` refers to the object the method was called on — so `this.balance` is the account's own balance.",
        starterCode: [
          "// One object holding state (balance) and behaviour (deposit, withdraw).",
          "const account = {",
          "  owner: 'Ada',",
          "  balance: 100,",
          "",
          "  deposit(amount) {",
          "    // TODO: add `amount` to this account's balance",
          "  },",
          "",
          "  withdraw(amount) {",
          "    // TODO: subtract `amount` from this account's balance",
          "  },",
          "",
          "  describe() {",
          "    return this.owner + ' has ' + this.balance;",
          "  },",
          "};",
          "",
          "console.log(account.describe());",
          "account.deposit(50);",
          "console.log(account.describe());",
          "account.withdraw(30);",
          "console.log(account.describe());",
        ].join("\n"),
        body: [
          "Fill in the two methods. Both change the *same* `balance`, which is the point:",
          "the data and the operations that are allowed to touch it live together.",
          "",
          "Once it works, try calling `account.withdraw(1000)`. Nothing stops you. That is a",
          "real gap, and closing it is what the encapsulation module is about — an object that",
          "merely groups its data has not yet protected it.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Identity is not equality",
        body: [
          "Two objects with identical contents are still two objects.",
          "",
          "```js",
          "const a = { balance: 100 };",
          "const b = { balance: 100 };",
          "a === b;  // false",
          "```",
          "",
          "`===` on objects asks *are these the same object*, not *do these look alike*. Both",
          "variables describe a balance of 100, but they are two separate values in memory, so",
          "changing `a.balance` leaves `b.balance` untouched.",
          "",
          "The mirror image is aliasing:",
          "",
          "```js",
          "const c = a;",
          "c.balance = 0;",
          "a.balance;  // 0 — c and a are the SAME object",
          "```",
          "",
          "This is the single most common surprise for people arriving from languages where",
          "assignment copies. Assignment copies the *reference*, not the object. Two names, one",
          "object, and a change through either name is visible through both.",
          "",
          "Some objects genuinely *should* be compared by contents — an amount of money, a date,",
          "a coordinate. Those are value objects, and making them behave that way takes",
          "deliberate work: an `equals` method, or `__eq__` and `__hash__` in Python. It is not",
          "the default, and it is covered later in this track.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Does === report them equal?",
        prompt:
          "Two objects are created separately with exactly the same fields and values. What does `===` report?",
        options: [
          {
            text: "false — they are two distinct objects, however similar their contents",
            correct: true,
          },
          { text: "true — all their fields are equal, so the objects are equal" },
          { text: "true, but only while neither object has been modified" },
          { text: "It depends on how many fields the objects have" },
        ],
        explanation:
          "`===` on objects compares identity: whether both sides are the same object. Separately created objects never are, no matter how their fields compare. Comparing by contents is something you implement — an `equals` method, or `__eq__` in Python — not something the operator does for you.",
        body: [
          "Before you answer, predict it. Guessing right for the wrong reason is worth less",
          "than guessing wrong and finding out why.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "From one literal to a factory",
        language: "javascript",
        goal:
          "Write a factory function that returns a fresh, independent account on every call, then prove the two accounts do not share a balance.",
        hint:
          "The `balance` parameter is a separate local variable on each call, so each returned object closes over its own. Return an object literal that reads and writes it.",
        starterCode: [
          "// An object literal is ONE object. A factory returns a new one per call.",
          "function createAccount(owner, balance) {",
          "  // TODO: return an object with `deposit`, `withdraw` and `describe`,",
          "  // using the `owner` and `balance` parameters above.",
          "}",
          "",
          "const ada = createAccount('Ada', 100);",
          "const bo = createAccount('Bo', 100);",
          "",
          "ada.deposit(50);",
          "",
          "// If these print the same number, the accounts are sharing state.",
          "console.log(ada.describe());",
          "console.log(bo.describe());",
        ].join("\n"),
        body: [
          "A literal gives you exactly one object. The moment a program has two customers, you",
          "need a way to produce more — and a factory function is the simplest one: call it,",
          "get a new independent object.",
          "",
          "Watch for the mistake of declaring `balance` once *outside* the factory. Every",
          "returned object would then read and write the same variable, and depositing into one",
          "account would change the other. Shared state that nobody asked for is the exact",
          "failure the parallel-array example had, in a new costume.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "When an object is the wrong tool",
        body: [
          "Objects are not free, and not everything is one.",
          "",
          "**A pure calculation is a function.** `Math.max(a, b)` holds no state between calls",
          "and has nothing to protect. Wrapping it in a `MaxCalculator` class with a",
          "`calculate()` method adds a name to learn, an instance to create, and no guarantee",
          "that a function did not already give you.",
          "",
          "**A single value is a value.** A temperature is a number. It becomes worth making",
          "into an object when it starts carrying a unit that must not be mixed up, or a range",
          "it must stay inside — that is, when there is an *invariant* to keep.",
          "",
          "**A bag of unrelated fields is a bag.** If a `Utils` object's fields never interact,",
          "grouping them together tells a reader nothing. The useful test is not \"could these",
          "be one object\" but \"do these change together, and is there a rule about them that",
          "somebody has to keep true?\" When the answer is yes, an object is where that rule",
          "goes and where it can be enforced. When the answer is no, an object is decoration.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "oop-classes-and-constructors",
    track: "oop",
    title: "Classes and Constructors",
    summary:
      "A class is a template that guarantees every instance starts life with the fields its methods assume exist.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/js/js_classes.asp",
      "https://www.w3schools.com/python/python_class_init.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "Template, instance, constructor",
        body: [
          "A factory function works, but it repeats the shape of the object at every return",
          "statement, and nothing says two factories were meant to produce the same kind of",
          "thing. A **class** names the shape once.",
          "",
          "```js",
          "class Rectangle {",
          "  constructor(width, height) {",
          "    this.width = width;",
          "    this.height = height;",
          "  }",
          "  area() { return this.width * this.height; }",
          "}",
          "```",
          "",
          "The class is the template; `new Rectangle(3, 4)` is an **instance**. The constructor",
          "runs once per instance and exists for one job: leave the object in a state its",
          "methods can rely on. `area()` reads `this.width` without checking whether it exists,",
          "and that is only safe because the constructor is the single door in.",
          "",
          "That guarantee is the whole value. A method that has to start with",
          "`if (this.width === undefined)` is telling you the constructor did not do its job.",
        ].join("\n"),
        diagram: {
          title: "One template, many instances",
          frames: [
            {
              label: "The template",
              caption:
                "The class declares the fields and the methods once. It holds no data itself — there is nothing to read a width from yet.",
              code: "class Rectangle { constructor(w, h) {...} area() {...} }",
            },
            {
              label: "First instance",
              caption:
                "`new` allocates an object and runs the constructor against it. From this line on, this object's width and height exist.",
              code: "const a = new Rectangle(3, 4);  // a.area() === 12",
            },
            {
              label: "Second instance",
              caption:
                "A separate object with its own fields, sharing the same methods. Changing a.width cannot affect b.",
              code: "const b = new Rectangle(10, 2);  // b.area() === 20",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "A Rectangle class",
        language: "javascript",
        goal: "Write the constructor and the area method, then create two instances.",
        hint: "Assign the parameters onto `this` inside the constructor: `this.width = width;`.",
        starterCode: [
          "class Rectangle {",
          "  constructor(width, height) {",
          "    // TODO: store both on `this` so area() can read them",
          "  }",
          "",
          "  area() {",
          "    // TODO: return the area",
          "  }",
          "}",
          "",
          "const a = new Rectangle(3, 4);",
          "const b = new Rectangle(10, 2);",
          "console.log(a.area(), b.area());  // expect 12 20",
        ].join("\n"),
        body: [
          "Nothing surprising here — do it once so the shape is in your fingers.",
          "",
          "When it prints `12 20`, delete the assignments in the constructor and run it again.",
          "The error you get is the one every method in a class is trusting the constructor to",
          "prevent.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Constructors that refuse",
        body: [
          "A constructor can do more than assign. It can *decline*.",
          "",
          "```js",
          "constructor(width, height) {",
          "  if (width <= 0 || height <= 0) {",
          "    throw new RangeError('sides must be positive');",
          "  }",
          "  this.width = width;",
          "  this.height = height;",
          "}",
          "```",
          "",
          "Compare the two places that check could live. Checked in the constructor, a rectangle",
          "with a negative side never exists; there is no object to pass around, log, or store.",
          "Checked in `area()`, the invalid object exists, and now *every* method has to defend",
          "itself, forever, including the ones written next year by someone who did not read",
          "this file.",
          "",
          "This is what \"fail fast\" means concretely: reject at the boundary, so the rest of the",
          "code has fewer states to handle. The cost is that construction can now fail, and",
          "callers have to deal with that — which is honest, because the failure was always",
          "there. It was just being discovered later, further from its cause.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "A validating __init__",
        language: "python",
        goal:
          "Raise a ValueError from __init__ when either side is not positive, and show that the invalid object is never created.",
        hint:
          "`raise ValueError('...')` inside `__init__` aborts construction. Wrap the bad call in try/except to print the message rather than crashing the script.",
        starterCode: [
          "class Rectangle:",
          "    def __init__(self, width, height):",
          "        # TODO: raise ValueError if width or height is not > 0",
          "        self.width = width",
          "        self.height = height",
          "",
          "    def area(self):",
          "        return self.width * self.height",
          "",
          "",
          "good = Rectangle(3, 4)",
          "print('good area:', good.area())",
          "",
          "try:",
          "    bad = Rectangle(-1, 4)",
          "    print('this line should not run:', bad.area())",
          "except ValueError as err:",
          "    print('refused:', err)",
        ].join("\n"),
        body: [
          "Python's `__init__` is the same idea with different spelling. Note what the `except`",
          "branch proves: the name `bad` is never bound, because the object was never finished.",
          "There is no half-built rectangle anywhere for later code to trip over.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "What has to be true after the constructor?",
        prompt:
          "A class's methods read `this.width` without checking that it exists. What makes that safe?",
        options: [
          {
            text: "The constructor is the only way in, and it always leaves the field set",
            correct: true,
          },
          { text: "JavaScript initialises undeclared fields to 0 automatically" },
          { text: "The methods are declared after the constructor in the class body" },
          { text: "Nothing makes it safe; every method should check its own fields" },
        ],
        explanation:
          "The constructor is the single entry point for creating an instance, so whatever it guarantees on exit holds for the object's whole life. That guarantee is exactly what lets methods skip defensive checks. It is also why a constructor that assigns fields conditionally quietly removes the guarantee every method depends on.",
        body: "This is the question a class invariant answers, and it is worth being able to state.",
      },
      {
        kind: "explain",
        title: "Too many parameters, and what to do instead",
        body: [
          "JavaScript and Python both allow exactly one constructor per class, so \"overloading\"",
          "has to be done another way.",
          "",
          "**Named arguments** are the first move. `new Booking(true, false, true, 3)` is",
          "unreadable and every caller has to remember the order; `new Booking({ refundable:",
          "true, insured: false, priority: true, nights: 3 })` cannot be got wrong silently.",
          "Python has this built in as keyword arguments.",
          "",
          "**Static factory methods** are the second. `Rectangle.square(5)` and",
          "`Date.fromISO(text)` are constructors with names, and a name is where the intent",
          "goes. Two factories with the same parameter types are perfectly clear; two",
          "overloaded constructors with the same types are not expressible at all.",
          "",
          "**A builder** is the third, and it earns its keep only when the optional parts are",
          "many and interdependent. Eleven optional parameters is the signal. Three is not —",
          "reaching for a builder there costs a class and a fluent chain to save typing two",
          "object keys.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "oop-methods-and-identity",
    track: "oop",
    title: "Methods, `this` and `self`",
    summary:
      "Methods are functions that receive the object they were called on, and most early OOP bugs are that receiver arriving as something unexpected.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this",
      "https://www.w3schools.com/python/python_class_self.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "How a method receives its object",
        body: [
          "A method is a function with one extra input you never see written in the call: the",
          "object it was called *on*.",
          "",
          "In Python that input is explicit. `def deposit(self, amount)` declares it, and",
          "`account.deposit(50)` passes `account` as `self` automatically. The parameter list",
          "and the call site disagree by one, visibly, and once you know that the rest follows.",
          "",
          "In JavaScript it is implicit and, crucially, decided **at the call site** rather than",
          "where the method was defined. `account.deposit(50)` sets `this` to `account` because",
          "of the dot. Take the same function and call it without a dot and there is no object",
          "on the left, so there is nothing for `this` to be.",
          "",
          "That is the whole mechanism. Nearly every `this`-related bug is a method that got",
          "separated from its dot.",
        ].join("\n"),
        diagram: {
          title: "Where the receiver comes from",
          frames: [
            {
              label: "Called with a dot",
              caption:
                "The object to the left of the dot becomes `this`. The method reads this.balance and finds 100.",
              code: "account.describe()   // this === account",
            },
            {
              label: "The function is detached",
              caption:
                "A reference to the function is copied out. The function is identical; the dot is gone.",
              code: "const f = account.describe;",
            },
            {
              label: "Called without a dot",
              caption:
                "Nothing sits to the left of the call, so `this` is undefined in a class or module, and reading this.balance throws.",
              code: "f()   // TypeError: cannot read properties of undefined",
            },
            {
              label: "The dot is restored",
              caption:
                "bind fixes the receiver permanently, so the function can be passed anywhere and still know its object.",
              code: "const g = account.describe.bind(account);\ng()   // works",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Break `this` on purpose",
        language: "javascript",
        goal:
          "Detach a method from its object, call it, and read the error. Then predict what a callback would do.",
        hint:
          "`const f = counter.report;` copies the function. Calling `f()` provides no receiver.",
        starterCode: [
          "class Counter {",
          "  constructor() { this.count = 0; }",
          "  increment() { this.count += 1; return this.count; }",
          "  report() { return 'count is ' + this.count; }",
          "}",
          "",
          "const counter = new Counter();",
          "counter.increment();",
          "console.log(counter.report());   // fine: called with a dot",
          "",
          "// TODO: copy `counter.report` into a variable and call it. Read the error.",
          "// Then try passing `counter.report` to this helper and predict the result:",
          "function callTwice(fn) { fn(); fn(); }",
        ].join("\n"),
        body: [
          "This is a lab about reading an error message properly. `Cannot read properties of",
          "undefined (reading 'count')` is not telling you `count` is missing — it is telling",
          "you `this` is `undefined`, so there was nothing to look `count` up on.",
          "",
          "Passing a method to a callback (`setTimeout`, `addEventListener`, `array.map`) is the",
          "everyday version of this. The callback calls your function with no dot.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Arrow functions inherit `this` — the fix and the trap",
        body: [
          "An arrow function has no `this` of its own. It uses whatever `this` was in the scope",
          "where it was *written*. That single rule is both the standard fix and a standard trap.",
          "",
          "**The fix.** Inside a method, a callback written as an arrow sees the method's `this`:",
          "",
          "```js",
          "start() {",
          "  setInterval(() => this.tick(), 1000);   // `this` is the instance",
          "}",
          "```",
          "",
          "A `function () { this.tick(); }` there would fail, because the timer calls it with no",
          "receiver.",
          "",
          "**The trap.** An arrow cannot be a method that needs a receiver:",
          "",
          "```js",
          "const account = {",
          "  balance: 100,",
          "  describe: () => this.balance,   // `this` is NOT account",
          "};",
          "```",
          "",
          "The arrow captured `this` from the surrounding module scope, where it is not the",
          "object being defined — the object does not even exist yet on that line.",
          "",
          "The rule of thumb: arrows for callbacks *inside* methods, ordinary methods for the",
          "object's own behaviour.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Repair the detached call two ways",
        language: "javascript",
        goal:
          "Make the detached call work with `bind`, then again with an arrow-function wrapper, and compare what each one gives you.",
        hint:
          "`counter.report.bind(counter)` returns a new function with the receiver fixed. `() => counter.report()` keeps the dot inside the arrow.",
        starterCode: [
          "class Counter {",
          "  constructor() { this.count = 7; }",
          "  report() { return 'count is ' + this.count; }",
          "}",
          "const counter = new Counter();",
          "",
          "function callIt(fn) { console.log(fn()); }",
          "",
          "// 1. TODO: pass a bound version of counter.report to callIt",
          "// 2. TODO: pass an arrow function that calls counter.report() to callIt",
          "",
          "// Both should print 'count is 7'.",
        ].join("\n"),
        body: [
          "Both work; they are not equivalent.",
          "",
          "`bind` returns a *new function object* every time it is called. Binding inside a",
          "render function therefore produces a fresh function on every render, which defeats",
          "any comparison a framework does to decide whether a prop changed.",
          "",
          "The arrow wrapper keeps the dot inside itself, so the receiver is resolved at call",
          "time. It reads more clearly, and it lets you pass extra arguments explicitly, which",
          "is usually what you want.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Why is Python's `self` explicit?",
        prompt: "Python makes `self` a declared first parameter. What does that buy?",
        options: [
          {
            text: "The receiver is visible in the signature, so a method cannot be silently detached from its object",
            correct: true,
          },
          { text: "It makes attribute lookup faster at run time" },
          { text: "It allows a class to have more than one constructor" },
          { text: "It is required for inheritance to work" },
        ],
        explanation:
          "Making the receiver an ordinary parameter means it follows ordinary rules. `Counter.report` in Python is a plain function that visibly needs a Counter, so calling it with the wrong thing — or with nothing — is an obvious argument error rather than a mysterious `undefined`. The cost is writing `self` on every method, which is the trade Python chose.",
        body: "One design decision, one consequence. Name the consequence.",
      },
      {
        kind: "explain",
        title: "Returning `this` on purpose",
        body: [
          "A method that has nothing to report can return the object instead, which lets calls",
          "chain:",
          "",
          "```js",
          "query.where('active').orderBy('name').limit(10);",
          "```",
          "",
          "Each call returns `this`, so the next dot has something to attach to. It reads well",
          "when every step is a *configuration* of the same thing.",
          "",
          "It reads badly when the steps are unrelated actions. `order.pay().ship().refund()`",
          "hides four state changes behind one expression, and if `ship()` throws, you are left",
          "guessing how far the chain got. Chaining also removes the natural place to put a",
          "return value: a method cannot both return `this` and return the result you wanted.",
          "",
          "So chain configuration, not consequences. And be aware of the other convention:",
          "returning a *new* object rather than `this` gives you an immutable builder, where an",
          "abandoned chain cannot have mutated anything.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "oop-encapsulation-basics",
    track: "oop",
    title: "Encapsulation and Invariants",
    summary:
      "Hiding a field is not secrecy for its own sake; it is how you keep a rule about that field true no matter who is calling.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/js/js_class_private.asp",
      "https://www.w3schools.com/python/python_encapsulation.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "Invariant, public surface, private detail",
        body: [
          "An **invariant** is a statement about an object that must be true at every moment a",
          "caller can observe it. \"The balance is never negative.\" \"The list is always sorted.\"",
          "\"Exactly one option is marked correct.\"",
          "",
          "An invariant is only a rule if something enforces it. If `balance` is a public field,",
          "the rule is a comment, and any line of code anywhere can break it:",
          "",
          "```js",
          "account.balance = -5000;   // no method involved, no check run",
          "```",
          "",
          "Making the field private does not hide a secret. It reduces the number of places that",
          "can change it from *everywhere* to *the methods of this class*. That is a finite,",
          "reviewable list, which is what makes the rule checkable at all.",
          "",
          "So the public surface is not \"whatever callers happen to need\". It is the set of",
          "operations through which the invariant survives — chosen deliberately, and as small",
          "as it can be.",
        ].join("\n"),
        diagram: {
          title: "Who can break the rule",
          frames: [
            {
              label: "Public field",
              caption:
                "Every line in the program can assign to account.balance. The rule 'never negative' is enforced by hope.",
              code: "account.balance = -5000;   // allowed",
            },
            {
              label: "Private field",
              caption:
                "Only methods of the class can touch #balance. Outside code assigning to it is a syntax error, not a runtime surprise.",
              code: "account.#balance = -5000;  // SyntaxError",
            },
            {
              label: "The public door",
              caption:
                "withdraw() is now the only route to a smaller balance, so the check inside it is the check for the whole program.",
              code: "withdraw(n) { if (n > this.#balance) throw ...; }",
            },
            {
              label: "The leak that remains",
              caption:
                "Returning an internal array by reference hands out a private field under another name. Callers can mutate it, and the rule is broken again.",
              code: "get items() { return this.#items; }   // leak",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "A private balance",
        language: "javascript",
        goal:
          "Convert `balance` to a `#balance` private field, route all changes through methods, and confirm outside code cannot reach it.",
        hint:
          "Private fields must be declared in the class body (`#balance = 0;`) before they can be assigned in the constructor.",
        starterCode: [
          "class Account {",
          "  // TODO: declare #balance here",
          "",
          "  constructor(initial) {",
          "    if (initial < 0) throw new RangeError('initial balance cannot be negative');",
          "    this.balance = initial;      // TODO: use the private field",
          "  }",
          "",
          "  deposit(amount) {",
          "    if (amount <= 0) throw new RangeError('deposit must be positive');",
          "    this.balance += amount;      // TODO",
          "  }",
          "",
          "  withdraw(amount) {",
          "    // TODO: refuse to overdraw, then subtract",
          "  }",
          "",
          "  get balanceValue() { return this.balance; }   // TODO: read the private field",
          "}",
          "",
          "const a = new Account(100);",
          "a.deposit(50);",
          "console.log(a.balanceValue);",
          "",
          "try {",
          "  a.withdraw(10000);",
          "} catch (err) {",
          "  console.log('refused:', err.message);",
          "}",
        ].join("\n"),
        body: [
          "Get it working, then try to break it from outside the class. `a.balance = -1` will",
          "quietly create an unrelated public property called `balance` — harmless, and worth",
          "seeing, because it shows the private field is genuinely a different slot rather than",
          "a naming convention.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "A validating setter is not a public field",
        body: [
          "Getters and setters look like fields at the call site and behave like methods:",
          "",
          "```python",
          "class Account:",
          "    def __init__(self, balance):",
          "        self._balance = 0",
          "        self.balance = balance      # goes through the setter",
          "",
          "    @property",
          "    def balance(self):",
          "        return self._balance",
          "",
          "    @balance.setter",
          "    def balance(self, value):",
          "        if value < 0:",
          "            raise ValueError('balance cannot be negative')",
          "        self._balance = value",
          "```",
          "",
          "The gain is real: `account.balance = -5` now raises instead of corrupting the object,",
          "and the check lives in one place.",
          "",
          "But note what a setter does *not* give you. A setter accepts any single value that",
          "passes its own test, which means it cannot express a rule that spans two fields",
          "(\"`end` must be after `start`\") or one that depends on the current value (\"you may",
          "not withdraw more than you have\"). Those need a *named operation* — `withdraw`,",
          "`reschedule` — because the rule is about the transition, not the value.",
          "",
          "A setter for every private field is a public field with extra steps. The question to",
          "ask is not \"how do I let callers set this?\" but \"what are callers actually trying to",
          "do?\"",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "A @property with a validating setter",
        language: "python",
        goal:
          "Add a validating setter for `score`, then show that a direct assignment of an out-of-range value is refused.",
        hint:
          "Store the real value in `self._score`. The `@property` getter returns it; the `@score.setter` validates before assigning.",
        starterCode: [
          "class Result:",
          "    def __init__(self, score):",
          "        self.score = score          # routed through the setter below",
          "",
          "    @property",
          "    def score(self):",
          "        return self._score",
          "",
          "    @score.setter",
          "    def score(self, value):",
          "        # TODO: refuse anything outside 0..100 with a ValueError",
          "        self._score = value",
          "",
          "",
          "r = Result(72)",
          "print('score:', r.score)",
          "",
          "for attempt in (101, -1, 100):",
          "    try:",
          "        r.score = attempt",
          "        print('accepted', attempt)",
          "    except ValueError as err:",
          "        print('refused', attempt, '->', err)",
        ].join("\n"),
        body: [
          "Python has no truly private fields — `_score` is a convention, and",
          "`r._score = 999` will work. That is a deliberate language choice: the leading",
          "underscore says \"not part of the public surface\", and the language trusts you.",
          "",
          "It matters less than it sounds. Encapsulation's job is to make the *accidental* break",
          "impossible and the *deliberate* one obvious. `r._score = 999` is not something anyone",
          "writes by mistake, and it shows up in review.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Which one breaks the invariant?",
        prompt: "Which of these actually lets outside code break the object's rule?",
        options: [
          {
            text: "A getter that returns the internal array itself, because the caller can then mutate it",
            correct: true,
          },
          { text: "A getter that returns a private number by value" },
          { text: "A method that reads a private field and returns a formatted string" },
          { text: "A private field being read by another method of the same class" },
        ],
        explanation:
          "Returning the internal collection by reference hands out the private field under a different name. The caller can call `push` or `sort` on it and the object never finds out, so any rule the class maintained about that collection is now unenforced. Returning a copy, or a read-only view, or better a method that performs the operation the caller actually wanted, keeps the rule intact. Numbers and strings are copied on return, so those getters leak nothing.",
        body: "One of these is the classic leak. It is worth being able to spot in review.",
      },
      {
        kind: "explain",
        title: "Leaky encapsulation",
        body: [
          "The private keyword is easy. Not undoing it is the hard part.",
          "",
          "```js",
          "class Basket {",
          "  #items = [];",
          "  get items() { return this.#items; }   // the leak",
          "}",
          "",
          "basket.items.push(anything);           // no validation ran",
          "basket.items.length = 0;               // basket silently emptied",
          "```",
          "",
          "Three ways out, in increasing order of how much they actually help:",
          "",
          "1. **Return a copy** — `[...this.#items]`. Cheap and obvious. Mutating the copy does",
          "   nothing, though a caller may be surprised that their change had no effect.",
          "2. **Return a read-only view** — `Object.freeze([...this.#items])`, or a generator so",
          "   callers can iterate but not index-assign. The failure becomes visible.",
          "3. **Do not return the collection at all.** Ask what the caller wanted. `total()`,",
          "   `count()`, `contains(sku)`, `add(item)` — each of those keeps the rule inside the",
          "   class, and the caller stops needing the array.",
          "",
          "The same leak has a quieter form: storing an array a caller passed *in* without copying",
          "it. The caller still holds a reference, so they can keep mutating your private state",
          "from outside. Copy on the way in as well as on the way out.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "oop-inheritance-first-look",
    track: "oop",
    title: "Inheritance, First Look",
    summary:
      "Inheritance says \"this kind of thing is a special case of that kind of thing\", and it is powerful exactly to the degree that claim is actually true.",
    level: "beginner",
    estimatedMinutes: 40,
    refs: [
      "https://www.w3schools.com/js/js_class_inheritance.asp",
      "https://www.w3schools.com/python/python_inheritance.asp",
    ],
    steps: [
      {
        kind: "explain",
        title: "Base and derived",
        body: [
          "A derived class starts with everything the base class has and adds or replaces parts",
          "of it.",
          "",
          "```js",
          "class Shape {",
          "  constructor(name) { this.name = name; }",
          "  describe() { return `${this.name} of area ${this.area()}`; }",
          "  area() { throw new Error('subclasses must implement area()'); }",
          "}",
          "",
          "class Circle extends Shape {",
          "  constructor(radius) {",
          "    super('circle');",
          "    this.radius = radius;",
          "  }",
          "  area() { return Math.PI * this.radius ** 2; }",
          "}",
          "```",
          "",
          "`Circle` inherits `describe()` and did not write it. It **must** supply `area()`,",
          "because `describe()` calls it — the base class has declared a hole and delegated it",
          "downward.",
          "",
          "Note what `super('circle')` is doing. The base constructor still needs to run; the",
          "derived class cannot skip it and still expect `this.name` to exist. Inheritance is",
          "*cooperation* between two constructors, not a copy-paste of one into the other.",
          "",
          "The claim inheritance makes is \"is-a\": a circle is a shape. If you find yourself",
          "saying \"well, mostly\", stop — the next module is about what to do instead.",
        ].join("\n"),
        diagram: {
          title: "What comes from where",
          frames: [
            {
              label: "Base declares",
              caption:
                "Shape supplies describe() and a name field, and declares area() as a hole its subclasses must fill.",
              code: "class Shape { describe() {...} area() { throw ... } }",
            },
            {
              label: "Derived extends",
              caption:
                "Circle gets describe() free. It adds radius and fills in area(). Nothing was copied.",
              code: "class Circle extends Shape { area() { ... } }",
            },
            {
              label: "Constructors cooperate",
              caption:
                "super('circle') runs the base constructor first, so this.name exists before Circle assigns this.radius.",
              code: "constructor(r) { super('circle'); this.radius = r; }",
            },
            {
              label: "The call resolves downward",
              caption:
                "describe() lives in Shape but the area() it calls is Circle's. The base class calls code that did not exist when it was written.",
              code: "circle.describe()  // 'circle of area 78.5...'",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "Extend a Shape base",
        language: "javascript",
        goal:
          "Write Circle and Square extending Shape, call super() correctly, and print both descriptions.",
        hint:
          "`super(...)` must be the first statement that touches `this` in a derived constructor.",
        starterCode: [
          "class Shape {",
          "  constructor(name) { this.name = name; }",
          "  area() { throw new Error('subclasses must implement area()'); }",
          "  describe() { return this.name + ' of area ' + this.area().toFixed(2); }",
          "}",
          "",
          "class Circle extends Shape {",
          "  constructor(radius) {",
          "    // TODO: call super with the name, then store the radius",
          "  }",
          "  // TODO: implement area()",
          "}",
          "",
          "class Square extends Shape {",
          "  // TODO: constructor and area()",
          "}",
          "",
          "console.log(new Circle(5).describe());",
          "console.log(new Square(4).describe());",
        ].join("\n"),
        body: [
          "`describe()` is written once in `Shape` and works for both subclasses without knowing",
          "either exists. That is the return on inheritance.",
          "",
          "Now make a third class that extends `Shape` and *forgets* `area()`. The error it",
          "throws is the base class refusing to guess — which is a better outcome than silently",
          "returning `undefined` and printing `area NaN` three screens later.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Overriding, and calling back into the base",
        body: [
          "Overriding replaces a base method for one subclass. Often you want to *extend* it",
          "rather than replace it, and `super.method()` is how:",
          "",
          "```js",
          "class Shape {",
          "  describe() { return `a ${this.name}`; }",
          "}",
          "class Circle extends Shape {",
          "  describe() { return `${super.describe()} with radius ${this.radius}`; }",
          "}",
          "```",
          "",
          "Two rules keep this honest.",
          "",
          "**An override must still do the job the base promised.** If `save()` persists in the",
          "base, an override that logs instead has broken every caller that relied on the",
          "promise, and none of them will get a compile error. This is the Liskov substitution",
          "principle, and it is a behavioural contract rather than a signature check — a",
          "language cannot verify it for you.",
          "",
          "**Deciding not to call `super` is a decision.** Sometimes correct, always worth a",
          "comment. Silently dropping the base's work is how a subclass ends up half-initialised",
          "or a resource ends up unreleased.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "`this` before `super()`",
        prompt:
          "In a JavaScript derived constructor, what happens if you touch `this` before calling `super()`?",
        options: [
          { text: "A ReferenceError is thrown — `this` does not exist yet", correct: true },
          { text: "It works; the base constructor runs automatically first" },
          { text: "`this` is an empty object and the assignment is silently lost" },
          { text: "It works, but only if the base constructor takes no arguments" },
        ],
        explanation:
          "In a derived class, `super()` is what brings `this` into existence — the base constructor is responsible for initialising the object. Until it has run, there is no `this` to read or assign, and the language says so with a ReferenceError rather than handing you a half-built object. Python differs: `self` already exists when `__init__` starts, so forgetting `super().__init__()` there gives you a silently under-initialised object, which is the more dangerous failure of the two.",
        body: "One of these is the actual behaviour, and the reason is worth knowing.",
      },
      {
        kind: "lab",
        title: "Override and call super()",
        language: "python",
        goal:
          "Override describe() in Circle so it extends the base version via super() rather than replacing it.",
        hint:
          "`super().describe()` returns the base result; build your string around it. Do not forget `super().__init__(...)`.",
        starterCode: [
          "class Shape:",
          "    def __init__(self, name):",
          "        self.name = name",
          "",
          "    def describe(self):",
          "        return 'a ' + self.name",
          "",
          "",
          "class Circle(Shape):",
          "    def __init__(self, radius):",
          "        # TODO: call the base __init__ with 'circle', then store the radius",
          "        pass",
          "",
          "    def describe(self):",
          "        # TODO: extend the base description with the radius",
          "        pass",
          "",
          "",
          "c = Circle(5)",
          "print(c.describe())",
          "",
          "# Now comment out your super().__init__ call and run again.",
          "# Python will not stop you -- read the error and note WHERE it appears.",
        ].join("\n"),
        body: [
          "Do the experiment in the last comment. Python raises `AttributeError: 'Circle' object",
          "has no attribute 'name'` — and it raises it inside `describe`, not inside",
          "`__init__`. The error surfaces at the first *use*, one step removed from the mistake.",
          "",
          "That distance is the general shape of inheritance bugs: the cause is in the",
          "constructor, the symptom is in a method, and the two can be far apart.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Depth is a cost",
        body: [
          "Three levels of inheritance is usually a smell. The reason is concrete, not stylistic.",
          "",
          "To understand what `Director.approve()` does when `Director extends Manager extends",
          "Employee extends Person`, you have to read four classes and work out which one",
          "actually supplies the method — and then which one supplies each method *it* calls.",
          "The behaviour of one object is distributed across four files, and no single file",
          "contains it.",
          "",
          "It gets worse when the base changes. The **fragile base class problem**: an edit to",
          "`Employee` that looks entirely local can break `Director`, because `Director` depends",
          "not on `Employee`'s interface but on its internals — which method calls which. Nothing",
          "in `Employee` declares that dependency, so nothing warns you.",
          "",
          "Deep hierarchies also model reality badly. Real taxonomies are not trees. A person is",
          "an employee *and* a customer; a document is printable *and* archivable. A tree forces",
          "you to pick one axis and then contort the rest.",
          "",
          "Two levels, a stable and genuinely closed set of subtypes, and no reaching into the",
          "base's internals: that is where inheritance is comfortable. Past that, composition",
          "does the same job with less coupling — which is the next module.",
        ].join("\n"),
      },
    ],
  },

  // -------------------------------------------------------------------------
  {
    slug: "oop-polymorphism-first-look",
    track: "oop",
    title: "Polymorphism, First Look",
    summary:
      "Polymorphism is the payoff: caller code that keeps working when you add a new kind of thing it has never heard of.",
    level: "beginner",
    estimatedMinutes: 35,
    refs: [
      "https://www.w3schools.com/python/python_polymorphism.asp",
      "https://refactoring.guru/design-patterns/strategy",
    ],
    steps: [
      {
        kind: "explain",
        title: "One call site, many implementations",
        body: [
          "Here is the shape polymorphism removes:",
          "",
          "```js",
          "function area(shape) {",
          "  if (shape.kind === 'circle') return Math.PI * shape.r ** 2;",
          "  if (shape.kind === 'square') return shape.side ** 2;",
          "  if (shape.kind === 'rect')   return shape.w * shape.h;",
          "  throw new Error('unknown shape');",
          "}",
          "```",
          "",
          "Adding a triangle means editing this function. And it is never the only one — there",
          "will be a matching chain in `perimeter`, in `draw`, in `serialise`. One new shape,",
          "four edits, in four files, and the compiler cannot tell you which one you missed.",
          "",
          "```js",
          "shapes.forEach(s => console.log(s.area()));",
          "```",
          "",
          "Now adding a triangle means *adding a class*. The loop is untouched, and it works for",
          "a shape written after it. The knowledge of how to compute an area has moved to the",
          "one place that already knows the shape's fields.",
          "",
          "That is the whole trade: dispatch by type test, in the caller, versus dispatch by",
          "method lookup, at the object.",
        ].join("\n"),
        diagram: {
          title: "Where the branching lives",
          frames: [
            {
              label: "Type test in the caller",
              caption:
                "The caller knows every shape by name. Each new kind means editing this function -- and the parallel chains in perimeter and draw.",
              code: "if (s.kind === 'circle') ... else if (s.kind === 'square') ...",
            },
            {
              label: "Each type knows itself",
              caption:
                "The formula moves next to the fields it needs. Circle owns the pi r squared; nobody else has to know it.",
              code: "class Circle { area() { return Math.PI * this.r ** 2; } }",
            },
            {
              label: "The caller stops asking",
              caption:
                "One call, no type test. This loop already works for shapes that will be written next year.",
              code: "for (const s of shapes) total += s.area();",
            },
            {
              label: "The cost",
              caption:
                "The set of cases is no longer visible in one place. Answering 'what are all the shapes?' now means searching the codebase, not reading one function.",
              code: "// grep 'extends Shape'",
            },
          ],
        },
      },
      {
        kind: "lab",
        title: "One loop, three shapes",
        language: "javascript",
        goal:
          "Compute the total area of a mixed array of shapes without a single type test, then add a fourth shape and confirm the loop needs no edit.",
        hint:
          "If every shape has an `area()` method, the loop only has to call it. Do not check what kind of shape it is.",
        starterCode: [
          "class Circle {",
          "  constructor(r) { this.r = r; }",
          "  area() { return Math.PI * this.r ** 2; }",
          "}",
          "class Square {",
          "  constructor(side) { this.side = side; }",
          "  area() { return this.side ** 2; }",
          "}",
          "class Rectangle {",
          "  constructor(w, h) { this.w = w; this.h = h; }",
          "  area() { return this.w * this.h; }",
          "}",
          "",
          "const shapes = [new Circle(1), new Square(2), new Rectangle(2, 3)];",
          "",
          "// TODO: total the areas. No `if`, no `instanceof`, no `.kind`.",
          "",
          "// TODO: add a Triangle class and push one onto `shapes`.",
          "// Your total line must not change.",
        ].join("\n"),
        body: [
          "The test of whether you got this right is not the number it prints. It is whether the",
          "line you wrote had to change when you added `Triangle`.",
        ].join("\n"),
      },
      {
        kind: "explain",
        title: "Duck typing versus declared interfaces",
        body: [
          "Both JavaScript and Python dispatch on whether the method *exists*, not on what the",
          "object was declared to be. If it has `area()`, it can go in the loop. That is duck",
          "typing, and it buys you real freedom: a test double, a mock, an object from a",
          "different library, all substitutable with no declaration and no adapter.",
          "",
          "What it costs is the error message. Pass in an object with no `area` and you find out",
          "at the moment of the call — possibly deep inside a loop, possibly in production, and",
          "the message names a missing property rather than a missing contract.",
          "",
          "A **declared interface** (Java, C#, TypeScript, a Python `Protocol`, a C++ abstract",
          "base) moves that failure earlier and names it better. `Triangle does not implement",
          "Shape: missing area()` at compile time is more useful than `s.area is not a function`",
          "at 3 a.m. It also documents the contract in a place a reader can find, which duck",
          "typing leaves implicit.",
          "",
          "Neither is the correct answer in general. What matters is that the contract exists in",
          "somebody's head either way — the only question is whether it is written down where a",
          "tool can check it.",
        ].join("\n"),
      },
      {
        kind: "lab",
        title: "Add a shape, change no caller",
        language: "python",
        goal:
          "Add a third shape to the list and confirm the reporting function needs no edit at all.",
        hint:
          "`report` only calls `area()` and `name()`. If your new class provides both, it already fits.",
        starterCode: [
          "class Circle:",
          "    def __init__(self, r): self.r = r",
          "    def name(self): return 'circle'",
          "    def area(self): return 3.141592653589793 * self.r ** 2",
          "",
          "class Square:",
          "    def __init__(self, side): self.side = side",
          "    def name(self): return 'square'",
          "    def area(self): return self.side ** 2",
          "",
          "",
          "def report(shapes):",
          "    \"\"\"Knows nothing about any specific shape. Do not edit this function.\"\"\"",
          "    for s in shapes:",
          "        print(f'{s.name():10s} {s.area():8.2f}')",
          "    print('total', round(sum(s.area() for s in shapes), 2))",
          "",
          "",
          "# TODO: write a Triangle class with name() and area(), then add one below.",
          "report([Circle(1), Square(2)])",
        ].join("\n"),
        body: [
          "`report` is the caller you are protecting. It has a docstring telling you not to edit",
          "it, and that constraint is the exercise.",
          "",
          "For the honest version of the trade-off: now try adding a shape that has `area()` but",
          "*not* `name()`. Nothing complains until `report` runs and reaches the missing method.",
          "That is duck typing's bill arriving.",
        ].join("\n"),
      },
      {
        kind: "check",
        title: "Which class gains a method?",
        prompt:
          "You are replacing `switch (payment.kind) { case 'card': ... case 'cash': ... }` with polymorphic dispatch. Where does each branch's body go?",
        options: [
          {
            text: "Into a method on each payment type, so the caller just calls it",
            correct: true,
          },
          { text: "Into a static helper class that the switch calls instead" },
          { text: "Into the caller, as a lookup table keyed by `kind`" },
          { text: "Into the base class, which keeps the switch but hides it" },
        ],
        explanation:
          "Each branch becomes a method on the type that branch was about. The caller then holds no knowledge of the type set at all, so adding a payment type means adding a class rather than editing the caller. A lookup table is a real improvement over a switch — it is data instead of control flow — but the caller still owns the mapping, so it still has to be edited for every new type. Keeping the switch inside a base class only moves it.",
        body: "This is the refactor you will actually be asked to do most often.",
      },
      {
        kind: "explain",
        title: "Where polymorphism costs you",
        body: [
          "Polymorphism is not free, and the cost is legibility of the whole.",
          "",
          "**You lose the list.** A `switch` shows you every case in fifteen lines. Polymorphic",
          "dispatch scatters them across files, and \"what are all the payment types?\" becomes a",
          "search rather than a read.",
          "",
          "**You lose the compiler's exhaustiveness check.** In a language with tagged unions, a",
          "`switch` that forgets a case is a compile error. Add a subclass that forgets to",
          "override a method and you get inherited behaviour that may be wrong — silently.",
          "",
          "**Debugging costs a hop.** A stack trace tells you `area()` was called; which `area()`",
          "depends on run-time type, and finding out means inspecting the object.",
          "",
          "So the honest rule: polymorphism pays when the set of types is *open* and grows.",
          "When the set is genuinely closed and small — three tax bands, four HTTP verbs — an",
          "explicit switch in one place is often clearer, and in a typed language it comes with",
          "a guarantee that a subclass hierarchy cannot give you.",
        ].join("\n"),
      },
    ],
  },
];
