-- Generated by `npm run db:generate` (async-queues stream), then EDITED. What was
-- changed and why is stated here rather than left for the next reader to notice.
--
-- THE INTENDED CHANGE is `mail_dispatches` — the ledger that closes the queue's
-- double-send hole. See src/db/schema.queue.ts for the argument.
--
-- `submission_ingest_runs` IS ALSO IN THIS FILE, and it is not this stream's
-- table. It appears because that table exists in the shared database but in no
-- migration, so snapshot 0003 does not know about it and ANY diff taken after it
-- necessarily includes it. Two things follow:
--
--   * it must NOT be deleted from this file. A fresh database — which is exactly
--     what CI builds (.github/workflows/ci.yml runs `db:migrate` against an empty
--     postgres:18 service) — never gets that table today, because no migration
--     creates it. Removing these statements while snapshot 0004 records the table
--     as existing would make that gap permanent and silent.
--   * it must not FAIL on a database that already has it. The shared development
--     database does. So the three statements for that table are guarded with
--     IF NOT EXISTS / a catalogue check, which converges to the same end state
--     whether the table is already there or not.
--
-- The `mail_dispatches` statements are left exactly as generated and are NOT
-- guarded: this stream's table is genuinely new, so a duplicate there would mean
-- something a migration should refuse to paper over.

CREATE TABLE IF NOT EXISTS "submission_ingest_runs" (
	"id" serial PRIMARY KEY NOT NULL,
	"assignment_id" integer NOT NULL,
	"ran_at" timestamp with time zone DEFAULT now() NOT NULL,
	"triggered_by" varchar(16) NOT NULL,
	"sheet_source" varchar(16) NOT NULL,
	"aborted" varchar(32),
	"detail" text,
	"rows_seen" integer DEFAULT 0 NOT NULL,
	"inserted" integer DEFAULT 0 NOT NULL,
	"updated" integer DEFAULT 0 NOT NULL,
	"unchanged" integer DEFAULT 0 NOT NULL,
	"skipped_count" integer DEFAULT 0 NOT NULL,
	"skip_reason_counts" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"skipped_sample" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"duration_ms" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mail_dispatches" (
	"id" serial PRIMARY KEY NOT NULL,
	"dedupe_key" varchar(200) NOT NULL,
	"channel" varchar(32) DEFAULT 'email' NOT NULL,
	"recipient" varchar(320) NOT NULL,
	"message_id" varchar(200),
	"attempts" integer DEFAULT 1 NOT NULL,
	"claimed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sent_at" timestamp with time zone,
	"failed_at" timestamp with time zone,
	"last_error" text
);
--> statement-breakpoint
DO $$ BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'submission_ingest_runs_assignment_id_assignments_id_fk'
	) THEN
		ALTER TABLE "submission_ingest_runs"
			ADD CONSTRAINT "submission_ingest_runs_assignment_id_assignments_id_fk"
			FOREIGN KEY ("assignment_id") REFERENCES "public"."assignments"("id")
			ON DELETE cascade ON UPDATE no action;
	END IF;
END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "submission_ingest_runs_assignment_idx" ON "submission_ingest_runs" USING btree ("assignment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "mail_dispatches_dedupe_key_idx" ON "mail_dispatches" USING btree ("dedupe_key");--> statement-breakpoint
CREATE INDEX "mail_dispatches_sent_at_idx" ON "mail_dispatches" USING btree ("sent_at","claimed_at");
